### ISSUE TITLE
Simplified Chinese translation issues

### ISSUE THREAD

**Issue by stevenlele** [transmission-remote-gui/transgui#1024]
The current translation is roughly done and the quality is quite terrible. There are a lot of wrong translations and inappropriate expressions. I have gone through the translation and fixed a huge number of mistakes, and got untranslated texts in v5.10 done.

### Small problems ###
- [ ] Line 9: `%s%s%d downloading, %d seeding%s%s, %s` Please provide context, what the %s and %d are. I have added `#9` temporarily in both end in Chinese version.
- [ ] Line 85: `in swarm` Please provide context. I left it untranslated and have added `#85` temporarily in both end.
- [ ] Line 360: `The maximum history of directories for storage of torrents` Please explain what this is.
- [ ] Line 362: In v5.10 `Template:` does not work. Nor does `Template`. Incidentally, what is this used to do and how?

### A bigger one ###
- [ ] Please include all the full stops (`.`) in the localization strings. Chinese full stops are different (`。`) and cannot be translated well in current situation.

### Small question to be discussed with Chinese speaker ###
- "Torrent" is left untranslated because "seed (种子)" is not a proper way to call it.

~~**Translation file here:**~~
~~transgui.zh.txt~~
Commit https://github.com/leonsoft-kras/transmisson-remote-gui/commit/929cce371783543b9f569f677e7be5a06e6639b0

Translator: stevenlele

~~PS: It would be better if I could be granted permission to edit transgui.zh file directly. Thanks for the great software.~~ Thanks!

**Comment by PeterDaveHello** [comment]
I think you mean Simplified Chinese, I'll take a look soon.

**Comment by PeterDaveHello** [comment]
I'm not very sure about this term:
`Ask for password=不提供密码`

Also I'd like to ask if you can invite few developers who can help review Simplified Chinese translation to +1 here, so we can have confidence on this update, what do you think?

BTW, looks like this translation is not based on the latest translation template, @stevenlele would you like to add just few more translation based on the latest template? You can refer to the Traditional Chinese translation if you won't mind, thanks.

**Comment by stevenlele** [comment]
@PeterDaveHello
- Regarding `Ask for password=不提供密码`, this basically asks TGUI to not provide password and ask Transmission host for the password. So `不提供密码` (_I'm_ not providing password) is better here in Chinese, otherwise it would become `要求密码` (ask _me_ for password).
- Regarding translation reviews, I do not know anyone that can do this work, but I'm pretty confident in the quality. (at least it's a lot better than the previous one, I checked some other torrent software for suggestions)
- I used the template in v5.10. Maybe the version in the code has more texts, I'll do that later. Trad. Chinese is pretty different and I'm afraid I cannot do that.
Don't forget the small problems. Cheers.

**Comment by PeterDaveHello** [comment]
@stevenlele I see a commit referred to this issue, so I think maybe you can directly send a pull request here for review? Thanks.

**Comment by stevenlele** [comment]
@PeterDaveHello
Sorry for the commit. Shall I revert it and send a pull request?

**Comment by PeterDaveHello** [comment]
Oops, as it's added in the master branch, maybe not, and I think we can close this issue now, as it's updated/added, thanks.

**Comment by stevenlele** [comment]
@PeterDaveHello How about the issues I referred to on top? Start a new issue?

**Comment by PeterDaveHello** [comment]
Oops, sorry that I forgot it.

**Comment by PeterDaveHello** [comment]
To clearify Traditional and Simplified Chinese, I updated the issue title.

BTW: v5.11.0 released here: https://github.com/leonsoft-kras/transmisson-remote-gui/releases/tag/v5.11.0 with this Simplified Chinese translation update.
