### ISSUE TITLE
How to permanently hide Status Bar Sizes

### ISSUE THREAD

**Issue by KronK0321** [transmission-remote-gui/transgui#1034]
Since the introduction of Status Bar Sizes in transgui 5.6, I have been unable to find a way to keep them disabled.

Choosing `View` --> `Status bar - Sizes` only disables them for the current session and does not appear to be saved to transgui.ini.

I am running Ubuntu 17.10 and Transmission Remote GUI 5.12 Build d141655.

I've tried manually editing transgui.ini to make the panels 0-width to no change:
```
[StatusBarPanels]
ScreenWidth=1920
0=354
1=165
2=165
3=0
4=0
5=0
6=0
7=0
```
I've set panels 3, 4, 5, 6, and 7 to 1px and that successfully removes all but the 7th panel (the one that displays Remaining:) which still persists.

I just want to return to the pre transgui-5.6 behaviour of the status bar. How can I do that?

**Comment by antekgla** [comment]
Currently there is no way.
When introduce this in 5.6 sadly I dont save in transgui.ini the status of StatusBarSizes.
The only way to disable permanently is uncheck StatusBar.
Give me some time. I wil fix it in a brief time.

**Comment by antekgla** [comment]
Done! [](https://github.com/transmission-remote-gui/transgui/commit/8efce84b234800e1d9605930b804a899d8ab3b14)
Now the StatusBarSize Menu Option status is saved in transgui.ini

**Comment by KronK0321** [comment]
> Curiosity: why you dont want this info in the status bar?

It's information that I haven't found a need for and adds to the clutter on the bar. I'm seeding ~1700 torrents, a good chunk of which are hard linked files to cross-seed multiple torrents with the same data. 

At-a-glance information about current bandwidth (and the cap in parentheses is a welcome addition) as well as free space on the array -- definitely helpful. Selecting 5 torrents that are all seeding the same data and transgui telling me 250GB of torrents -- not so much.

> Done! 8efce84
> Now the StatusBarSize Menu Option status is saved in transgui.ini

Thank you very much!
