### ISSUE TITLE
Lazarus 1.8.0 support

### ISSUE THREAD

**Issue by KottV** [transmission-remote-gui/transgui#1037]
Hi all

As new version of lazarus released recently, do you plan to update sources for support it?
I've mad some dirty hacks in code  and transgui compiles successfully under 1.8.0rcX even with Qt5-frontend. But I am not sure if my workarounds acceptable. If you mind I can publish my "patches".

**Comment by leonsoft-kras** [comment]
Hello!
Thanks, but I think it's too early. When a stable release of the lazarus comes out, then you can check the compilation. Now make corrections to the working version for the sake of incomprehensible new bugs - this is to get a lot of unnecessary questions from users.

**Comment by KottV** [comment]
Just released.

**Comment by spleenjack** [comment]
Hope these fixes is ok: https://github.com/transmission-remote-gui/transgui/pull/1040
