### ISSUE TITLE
transmission-remote-gui is crashing with latest Mac OS

### ISSUE THREAD

**Issue by mindej** [transmission-remote-gui/transgui#1039]
Mac OS X v 10.13.1

![image](https://user-images.githubusercontent.com/1636250/33672823-df4db294-dab3-11e7-8ed5-0106a106b000.png)

![image](https://user-images.githubusercontent.com/1636250/33672879-06836200-dab4-11e7-89ad-cf0f8c64578d.png)

![image](https://user-images.githubusercontent.com/1636250/33672865-fbd013da-dab3-11e7-8f7c-5e6bb1c22e25.png)

**Comment by PeterDaveHello** [comment]
I didn't face this problem, please describe what's the task you're doing right before the problem, thanks.

**Comment by acerus** [comment]
Same error. Program just won't start and can only be terminated via System Monitor

**Comment by PeterDaveHello** [comment]
Do you know any previous version of transgui that you can use properly without any problem?
I'll also test it later.

**Comment by mindej** [comment]
I got this error with v 5.10 downloaded from https://sourceforge.net/projects/transgui/ after update to v 5.12 the problem disappear. It works fine now for me. You should remove old version in sourceforge.net

**Comment by leonsoft-kras** [comment]
We are not related to the version on sourceforge.net

**Comment by mindej** [comment]
I am using your version now. It is better.
