### ISSUE TITLE
"From now" format for datetime columns

### ISSUE THREAD

**Issue by pasha-zzz** [transmission-remote-gui/transgui#1043]
Maybe optional.
Added/completed/last activity columns format like a "1h 33m ago" or "1d 11h 5m ago" and so on (w - week, m - month, y - year).

**Comment by pasha-zzz** [comment]
For date delta use PeriodBetween function:
https://www.freepascal.org/docs-html/rtl/dateutils/periodbetween.html

Only affected function - TMainForm.TorrentDateTimeToString

**Comment by pasha-zzz** [comment]
Localization and option to enable this format needed. But something like:

function PeriodName(per: word; pername: string): string;
begin
  if per=0 then Result:='' else Result:=IntToStr(per) + ' ' + pername + ' ';
end;

function TMainForm.TorrentDateTimeToString(d: Int64): string;
var dt, dt1: TDateTime;
  dd, dm, dy: word;
  s: string;
begin
  if d = 0 then
    Result:=''
  else
    begin
//    Result:=DateTimeToStr(UnixToDateTime(d) + GetTimeZoneDelta);
      dt:=UnixToDateTime(d) + GetTimeZoneDelta;
      dt1:=Now;
      PeriodBetween(dt1, dt, dy, dm, dd);
      dt1:=Abs(Frac(dt-dt1));
      s:=PeriodName(dy, 'y') + PeriodName(dm, 'mo') + PeriodName(dd, 'd') + PeriodName(Trunc(dt1*24), 'h') + PeriodName(Trunc(dt1*24*60) mod 60, 'm') + PeriodName(Trunc(dt1*24*60*60) mod 60, 's');
      if Length(s)=0 then s:='0 s';
      s:=s+'ago';
      Result:=s;
    end;
end;

**Comment by pasha-zzz** [comment]
Or (even better):

function TMainForm.TorrentDateTimeToString(d: Int64): string;
var dt, dt1: TDateTime;
  dd, dmo, dy, dh, dm, ds: word;
  s: string;
begin
  if d = 0 then
    Result:=''
  else
    begin
//    Result:=DateTimeToStr(UnixToDateTime(d) + GetTimeZoneDelta);
      dt:=UnixToDateTime(d) + GetTimeZoneDelta;
      dt1:=Now;
      PeriodBetween(dt1, dt, dy, dmo, dd);
      dt1:=Abs(Frac(dt-dt1));
      s:=PeriodName(dy, 'y') + PeriodName(dmo, 'mo') + PeriodName(dd, 'd');
      if dy+dmo=0 then
      begin
        dh:=Trunc(dt1*24);
        s:=s+PeriodName(dh, 'h');
        if dd=0 then
        begin
          dm:=Trunc(dt1*24*60) mod 60;
          s:=s+PeriodName(dm, 'm');
          if dh=0 then
          begin
            ds:=Trunc(dt1*24*60*60) mod 60;
            PeriodName(ds, 's');
          end;
        end;
      end;
      if Length(s)=0 then s:='0 s';
      s:=s+'ago';
      Result:=s;
    end;
end;

**Comment by leonsoft-kras** [comment]
ok, thanks 👍

**Comment by antekgla** [comment]
I'm working on this...
I think what is better to make it **optional** modifying the **TorrentDateTimeToString** function adding a new optional parameter:
```pascal
function TorrentDateTimeToString(d: Int64; FromNow:Boolean = false): string;
```
Then make a new boolean value in transgui.ini and read it in Oncreate of the form.
```pascal
  FFromNow := Ini.ReadBool('Interface','FromNow',false);
```

And not hardcode the name of y, mo, d, h, m, s for translations purposes. 
Something like this:

```pascal
function HumanReadableTime(ANow,AThen: TDateTime): string;
var
  Years, Months, Days, Hours, Minutes, Seconds, Discard: Word;
begin
  Try
    PeriodBetween(ANow,AThen,Years,Months,Days);
    DecodeDateTime(Anow-AThen,Discard,Discard,Discard,Hours,Minutes,Seconds,Discard);
    if Years > 0 then begin
       Result := Format(sYears,[Years]) + ' ' + Format(sMonths,[Months]);
    end else if Months > 0 then begin
      Result := Format(sMonths,[Months]) + ' ' + Format(sDays,[Days]);
     end else if Days > 0 then begin
       Result := Format(sDays,[Days]) + ' ' + Format(sHours,[Hours]);
    end else if Hours > 0 then begin
      Result := Format(sHours,[Hours]) + ' ' + Format(sMins,[Minutes]);
    end else if Minutes > 0 then begin
      Result := Format(sMins,[Minutes]) + ' ' + Format(sSecs,[Seconds]);
    end else begin
      Result := Format(sSecs,[Seconds])
    end;
  Except
    Result := 'An Eternity';
  End;
end;

function TMainForm.TorrentDateTimeToString(d: Int64; FromNow: Boolean): string;
begin
  if d = 0 then
    Result:=''
  else
      if FromNow then
         Result := HumanReadableTime(Now,UnixToDateTime(d) + GetTimeZoneDelta) else
             Result:=DateTimeToStr(UnixToDateTime(d) + GetTimeZoneDelta);
end; 
```

So, then you have to replace every call to **TorrentDateTimeToString** with the new optional parameter like this:

```pascal
procedure TMainForm.gTorrentsCellAttributes(Sender: TVarGrid; ACol, ARow, ADataCol: integer; 
AState: TGridDrawState; var CellAttribs: TCellAttributes);
...
     Text:=TorrentDateTimeToString(Sender.Items[ADataCol, ARow],FFromNow);
...
```

**Comment by leonsoft-kras** [comment]
@antekgla - try :) good luck to you !

**Comment by pasha-zzz** [comment]
I wrote that it needs localization and option support. And I think there is no need to add additional parameter to function, we can read option directly in TMainForm.TorrentDateTimeToString function

**Comment by antekgla** [comment]
> And I think there is no need to add additional parameter to function, we can read option directly in TMainForm.TorrentDateTimeToString function

I also consider that, but for example in my current Transmission setup with 300 torrents and columns Completed On, Added On & Last Active that would be 900 reads to the ini file every time TransGUI draw the torrent grid (in my case each 5 seconds)
I think what is better read it only once at form creation.

**Comment by pasha-zzz** [comment]
>  I think what is better read it only once at form creation
New property like TMainForm.FFromNow solves this. And arguments of TMainForm.TorrentDateTimeToString untouched. And again, I dont wrote "read directly from file"...

**Comment by antekgla** [comment]
Wel... I finally  implement this. 
I make a Pull Request (like @PeterDaveHello suggest) to merge the code from this new feature.

If you want to display the Date/Times in a Relative Form (to Now) add a new value in _transgui.ini_ in the **[Mainform]** section:

`FromNow=1`

where **1=** Relative Times and **0 or missing=** MM/DD/YY HH:MM:SS

In both cases I implement the possibility of view the Date/Time in the other way.
I did that thru hints:

**If you view Relative Times the hint shows you Absolute Times:**

![hin1](https://user-images.githubusercontent.com/24402722/35006578-add9e6b4-fad5-11e7-9b47-e6409c432193.jpg)

![hint2](https://user-images.githubusercontent.com/24402722/35006596-b6fda474-fad5-11e7-9be9-b357d989ef13.jpg)

**If you view Absolute Times the hints shows Relative Times:**

![hint3](https://user-images.githubusercontent.com/24402722/35006619-cba6821a-fad5-11e7-8beb-19dea5c84bb0.jpg)

![hint4](https://user-images.githubusercontent.com/24402722/35006625-d1eac91a-fad5-11e7-8498-33fbfd80a87d.jpg)

**Comment by PeterDaveHello** [comment]
@antekgla awesome 👍
