### ISSUE TITLE
Provide Windows 64-bit build

### ISSUE THREAD

**Issue by PeterDaveHello** [transmission-remote-gui/transgui#1047]
I've tested with building the 64-bit binary, but need few more tests and integrate with the build process.

**Comment by setsunakawa** [comment]
up :)

**Comment by qingxin6174** [comment]
I hope 64-bit comes earlier.

**Comment by PeterDaveHello** [comment]
@qingxin6174 contributions are welcome ;)

**Comment by PeterDaveHello** [comment]
@setsunakawa @qingxin6174 
I've uploaded 64bit build of Windows release here, would you like to help test it?
https://github.com/transmission-remote-gui/transgui/releases/tag/v5.17.0

**Comment by PeterDaveHello** [comment]
cc #1238

**Comment by setsunakawa** [comment]
64b seems to works for me, gg 👍
The setup is trying to install in `C:\Program Files (x86)` whereas it should install in `C:\Program Files`

**Comment by PeterDaveHello** [comment]
@setsunakawa Nice catch! Thanks for the feedback!

**Comment by a10kiloham** [comment]
upgrading from 5.01 to 5.17 with the 64b experimental gives SSL error that ssleay DLLs can't be found.

**Comment by SignFinder** [comment]
Installation of transgui-5.17-setup-64bit_experimental.exe have fixed error with SSL for me.

**Comment by PeterDaveHello** [comment]
transgui-5.17-setup_64bit_experimental_2.exe was uploaded, should fix above issues, please help test it.
https://github.com/transmission-remote-gui/transgui/releases/tag/v5.17.0

**Comment by kz26** [comment]
For the most part the 64-bit build works well, although I do seem to get random crashes from time to time, especially if the program has been open for a while.

**Comment by PeterDaveHello** [comment]
@kz26 I assume that crashes also happend on 32-bit versions? Do you mind to help confirm it?

**Comment by PeterDaveHello** [comment]
Just published v5.18.0 with Windows 64bit build:
- https://github.com/transmission-remote-gui/transgui/releases/tag/v5.18.0
- https://github.com/transmission-remote-gui/transgui/commit/a0529f2449e16fc4688e0c1759c62b6a50c977f4
