### ISSUE TITLE
Main window should hide when tray icon clicked if already visible

### ISSUE THREAD

**Issue by blackwind** [transmission-remote-gui/transgui#1050]
Currently, clicking the tray icon shows the main window no matter what. I'd like to suggest that a tray icon click *hide* the main window if it's currently visible. This is a standard practice in most torrent clients and is great for checking your torrents and very quickly getting back to work.

**Comment by leonsoft-kras** [comment]
good offer. I'll try to implement.

**Comment by antekgla** [comment]
> good offer. I'll try to implement.

```
procedure TMainForm.TrayIconDblClick(Sender: TObject);
begin
{$ifndef darwin}
//  acShowApp.Execute;
if (MainForm.Visible = false) or (MainForm.WindowState = wsMinimized) then
    MainForm.ShowApp
    else
    MainForm.HideApp;
{$endif darwin}
end;  
```

**Comment by blackwind** [comment]
Looks good to me. Can you submit a pull request?

**Comment by antekgla** [comment]
If @leonsoft-kras dont have a better code I do it!

**Comment by leonsoft-kras** [comment]
I did it differently recently, but I'll try to see your version.

In general there was no time. I wanted to ask a question, but for now I'll look at your option.

**Comment by leonsoft-kras** [comment]
thanks!  beautiful solution))
