### ISSUE TITLE
Error when changing file location

### ISSUE THREAD

**Issue by duramato** [transmission-remote-gui/transgui#1057]
- Windows 10 
- transgui 5.13

When changing a torrent's file location, I get the following error:

![image](https://pls.gtfo.accountant/FmUmo.png)

But it still changes the file's location.

More info needed just ask

**Comment by leonsoft-kras** [comment]
1. Can you repeat the problem?
2. Can you send your ini-file?
     [Hosts] and [Connection ....] can be deleted from the file.

**Comment by duramato** [comment]
1. Yes, its reproducable
2. https://gist.github.com/duramato/2f1009af381da750fdf2a00ac5efb466

How to reproduce:

1. Right click torrent;
2. Change file location;
3. Add anything to the end of the existing path, to create a new directory. Like add "`123`" to "`/home/user/downloads`" it will become in the end"`/home/user/downloads/123`"; 
4. The error from the OP's scrreenshoot should show up;

**Comment by StentMan** [comment]
I'm experiencing the same problem when trying to set data location: 
Error: LS-008. Please contact the developer
I just recently reinstalled v5.13 and had to redo all the settings, including the path mappings. I think I got it right, since when I try to open containing folder everything opens just fine.

**Comment by panfren** [comment]
Happy new year! Same issue here as well.

**Comment by leonsoft-kras** [comment]
I could not repeat the situation on your information. I changed the code a bit, maybe this will help. It is necessary to try on your means.

**Comment by rd1** [comment]
same as op, i change location, error pops up but still does the work.

**Comment by rd1** [comment]
also the set data location window doesn't save paths anymore. fresh new install of win10 and fresh transgui 5.13 (only version installed).

only 2 paths in ini file, original from transmission qt , and other one is from adding a new torrent. But moving torrents doesn't add new folders to list.

**Comment by AOne-T** [comment]
Same problem. 
Win 10 1709 x64. TransGUI 5.13. 
Changing location (every time) pops this dialog. Transmission and locations are on a NAS.

**Comment by AOne-T** [comment]
I have to add. I found out that it only happend if I want to relocate downloaded torrent to the "new" location that is not in the recent list. If I move to the "known" location - there is no error, but if I move to "new" location - I have this error and this location doesn't save in recent list.

**Comment by rd1** [comment]
i agree, if a path exists its fine, but a new one generates this error and isn't added to the list.

**Comment by elisimpson** [comment]
I have the same issue. Error LS-008, files are moved anyway, folder location isn't added to the list. Synology NAS.

**Comment by leonsoft-kras** [comment]
waiting for the next release.
In the meantime, everyone can write "I have the same"
Maybe someone from this information will get better: D

**Comment by rd1** [comment]
works fine once again, thanks

**Comment by elisimpson** [comment]
Tested with latest version. The error when moving files is gone, but the new location is still not saved into the list of previously used locations. Here's the relevant part of my .ini file if that helps:

[AddTorrent.DiskStation (LAN)]
PeerLimit=60
FolderCount=1
Folder0=/volume1/download
FolHit0=25
FolExt0=
LastDt0=04.02.2018
Folder1=
FolHit1=-1
FolExt1=
LastDt1=
LastDownloadDir=/volume1/download
LastMoveDir=/volume1/video/Music/Dempagumi.inc/Concert

**Comment by cociweb** [comment]
The error is appeared on 5.14. The move is successful, but the old folder is kept.

**Comment by leonsoft-kras** [comment]
I can't repeat your situation. This function works for me and there is no malfunction.
Minor changes in the function of the result did not bring.

Put a breakpoint in the function and go under the debugger. Tell us where the exception occurs.

**Comment by AOne-T** [comment]
> Tested with latest version. The error when moving files is gone, but the new location is still not saved into the list of previously used locations. 
Me too. Tested on another machine, but the result is the same.

**Comment by AOne-T** [comment]
@leonsoft-kras: you mean about the debugger?

**Comment by leonsoft-kras** [comment]
Yes. 
Why write "Me too" ? Tell me what's going on your computer. ))

**Comment by rd1** [comment]
still can't add new paths when moving files in 5.15 , it completes the move but not adding new paths.

**Comment by leonsoft-kras** [comment]
Of course. Did someone check the code under the debugger?

**Comment by AOne-T** [comment]
What IDE do you use?

**Comment by leonsoft-kras** [comment]
Lazarus

**Comment by AOne-T** [comment]
```
Project transgui.exe cast an exception 'EStringListError' with message:
Operation not allowed on sorted list

 At address 100082E1B
```
TMainForm.acMoveTorrentExecute -> SaveDownloadDirs
```
    if CurFolderParam = 'LastMoveDir' then begin
      if i < 0 then begin
          DeleteDirs (CB, 1);
          CB.Items.Insert   (0, selfolder);  <-- exception here
```

**Comment by leonsoft-kras** [comment]
Thank you.
It's strange that there are no exceptions to Windows.

**Comment by AOne-T** [comment]
Yes, it's somewhat suppressed by empty **expect** block, I think, where original LS-008 exception is commented out.

**Comment by AOne-T** [comment]
Checked. Works now!

**Comment by leonsoft-kras** [comment]
I repeat. At me the code worked completely, the data were added, exceptions did not occur. It is not the existence of an exception handling. 
Therefore, it is strange that in different systems the function works differently.

**Comment by AOne-T** [comment]
When will this issue be closed and released?

**Comment by leonsoft-kras** [comment]
The next release, when there will be some more corrections. Not every day.
Can be said @PeterDaveHello

**Comment by PeterDaveHello** [comment]
Will be soon :)

**Comment by PeterDaveHello** [comment]
https://github.com/transmission-remote-gui/transgui/releases/tag/v5.15.3

**Comment by rd1** [comment]
yes in deed it seems fixed, tested on win10 x64 , thank you PeterDaveHello !

**Comment by PeterDaveHello** [comment]
@rd1 the credits belong to @leonsoft-kras :)
