### ISSUE TITLE
Traditional Chinese translation issues

### ISSUE THREAD

**Issue by TonyRL** [transmission-remote-gui/transgui#1059]
@PeterDaveHello 

The status bar translation of `Remaining: %s=剩餘: %s` and `Free: %s=剩餘: %s` are misleading as shown.
![cht](https://user-images.githubusercontent.com/11386903/34461496-bf4e4b5e-ee66-11e7-9edc-9adabd6cf681.PNG)
You can't tell which of them are the remaining disk space available or the size left. 

But the English translation did its job well.
![eng](https://user-images.githubusercontent.com/11386903/34461515-595cefca-ee67-11e7-862b-997488243372.PNG)

It would be better if you can change it to `Free: %s=剩餘空間: %s` for https://github.com/transmission-remote-gui/transgui/blob/master/lang/transgui.zh_tw#L244

**Comment by PeterDaveHello** [comment]
Should be good now?
