### ISSUE TITLE
Mouse scrolls wrong way on v5.13 for Windows

### ISSUE THREAD

**Issue by JJRousseau** [transmission-remote-gui/transgui#1062]
I notice that the mouse scrolls in the opposite direction on the latest version 5.13 for Windows. Tested with a Logitech and Perixx mouse on Windows 10 1607.

**Comment by kissglay** [comment]
Rolling the wheel one notch scrolls like dozen lines at a time in 5.13, while the previous version respecting the setting made in "Control Panel -> Mouse Properties" in Windows.

**Comment by rd1** [comment]
did not notice the wrong or opposite direction scrolling

but did notice the number of lines scrolled is not consistent with windows mouse settings.

fresh new windows 10 v1709 installed last weekend

**Comment by mrfearless** [comment]
I recently updated from an older version and noticed this change as well, now the mouse scroll wheel scrolls a full page view of lines instead of a few lines at a time. I looked in the ini settings to see if there was a settings to adjust this back, but didnt see any.

**Comment by kissglay** [comment]
Introduced in 5.13, this issue persists in 5.14.

**Comment by JJRousseau** [comment]
Still not fixed in 5.15.2 . It still scrolls by a page regardless of the control panel setting as well.

**Comment by antekgla** [comment]
Can't reproduce this issue.
Tested **5.13** & **5.15.2** in **W7** and **W10** and the mouse wheel scroll normal (Logitech Trackball)

Can you test the file I update in #1101 (post number 12) ?
The reason I want to you test that file is what was compiled with Lazarus 1.6.
The official release is compiled with Lazarus 1.8.

**Comment by kissglay** [comment]
With the one provided, scrolling without problem. (Except this one can't load "libeay32.dll")
In my case, the one compiled with Lazarus 1.8 scroll the number of lines -- specified in windows mouse setting -- squared. e.g. 3 lines in setting became 9 lines while 5 lines became 25 lines.

**Comment by JJRousseau** [comment]
Scrolling works properly in that build, antekgla.

**Comment by rd1** [comment]
i've had this issue since a couple versions too

**Comment by antekgla** [comment]
I have reading Lazarus forums and I dont find a isssue with this and I tested myself in W10 and the issue is not present in my setup.
Maybe some related with HighDPI settings?
To The people what have this problems:
**... what is your Screen Resolution/DPI Settings?**

**Comment by kissglay** [comment]
Tested on 2 PC and 1 Laptop, same problem.
On the laptop, if using the touchpad gesture to scroll, it's fine and respect the setting (how many lines should be scrolled), but not if using a mouse.

**Comment by antekgla** [comment]
Fix this with https://github.com/transmission-remote-gui/transgui/commit/ab033d9e8359ef1c632f0d2e7c49f816abcf6277

Apparently original author make a fix for better scroll in TVarGrid. That fix works great until Lazarus 1.6 but in 1.8 the number of lines scrolled are incorrect.
This fix make that workaround conditional to Lazarus 1.6 or lower.

If anyone want to test this before release, please download this test build (only windows) compiled with Lazarus 1.8

[transgui.zip](https://github.com/transmission-remote-gui/transgui/files/1864124/transgui.zip)

**Comment by JJRousseau** [comment]
That build works properly when you have the mouse control panel set to scroll at x lines per notch but when you set it to scroll at one page at a time, it scolls one line per notch in the wrong direction.

**Comment by mrfearless** [comment]
I tried your build @antekgla and its much better.

**Comment by PeterDaveHello** [comment]
https://github.com/transmission-remote-gui/transgui/releases/tag/v5.15.3

**Comment by kissglay** [comment]
Thx @antekgla.
It's working properly now.

**Comment by JJRousseau** [comment]
Still doesn't work when setting scroll to one page at a time.

**Comment by antekgla** [comment]
I definitely (I hope) fix this with https://github.com/transmission-remote-gui/transgui/commit/4983a0f6d4ae1a7ca484f7ee1a8d7139c18bfe39

Test build before release (only Windows) here:

[transgui.zip](https://github.com/transmission-remote-gui/transgui/files/1865775/transgui.zip)

This was hard... Lazarus 1.8 has completely rewritten the **TCustomDrawGrid.GridMouseWheel** procedure and is incompatible with 1.6.

**Comment by JJRousseau** [comment]
This one scrolls properly in full page or multiline mode. Thanks antekgla.

**Comment by PeterDaveHello** [comment]
https://github.com/transmission-remote-gui/transgui/releases/tag/v5.14.4
