### ISSUE TITLE
Feature Request: Start paused by default

### ISSUE THREAD

**Issue by McJono** [transmission-remote-gui/transgui#1065]
After wanting to be able to just click on magnet links and add them to the list, I realized that I cannot do this without the downloads no being started paused.
Was hoping you could add a application setting that will always start paused.

**Comment by antekgla** [comment]
I assume you have unchecked the option **"Prompt for download options when adding a new torrent"** in Application Options.
If yes check that option and add a new torrent/magnet, a window with options appears, un-check **"Start Torrent"**, click OK.
From now all torrents would be added paused.
You can un-check **"Prompt for download options when adding a new torrent"** again if you want.

**Comment by McJono** [comment]
Sorry been busy so I wasn't able to check.
When I un-check start torrent it doesn't seem to remember that this has been unchecked. There also seems to be no setting kept in the transgui configuration folder.

Could this be because I used apt to install this instead of github release?

**Comment by McJono** [comment]
Ok never mind. With the newer version instead of Apt it was fine. Sorry that I didn't check that first.

**Comment by mbhkoay** [comment]
I was also facing this problem and was looking around at my transmission-daemon settings.json, with start-added-torrents: false. However when I dragged and dropped a torrent file into transmission gtk it starts automatically, while adding via the watch folder works as intended (added as paused state). antekgla's suggestion fixed this for me, but I would suggest that to add a toggle to the application settings as it would be more obvious. More of a quality of life improvement. 

> I assume you have unchecked the option **"Prompt for download options when adding a new torrent"** in Application Options.
> If yes check that option and add a new torrent/magnet, a window with options appears, un-check **"Start Torrent"**, click OK.
> From now all torrents would be added paused.
> You can un-check **"Prompt for download options when adding a new torrent"** again if you want.
