### ISSUE TITLE
Add torrent > "Templates"?

### ISSUE THREAD

**Issue by Dustie** [transmission-remote-gui/transgui#1069]
Could someone explain what the "Template" option is for in the Add Torrent dialogue? I can't seem to find anything about it here or looking at Transmission.

![capture](https://user-images.githubusercontent.com/21229918/35335299-787324f4-0115-11e8-90ec-1243365c1032.PNG)

**Comment by leonsoft-kras** [comment]
![default](https://user-images.githubusercontent.com/11468577/35336824-2c9efb70-014c-11e8-8c0d-8d95a057c60f.png)

**Comment by leonsoft-kras** [comment]
This is the way to automatically select the folder in which to download the torrent.

**Comment by rld243** [comment]
It's kinda unrelated to this question but could you please fix the text box position for the next release? It looks a bit ugly now.

![35336824-2c9efb70-014c-11e8-8c0d-8d95a057c60f](https://user-images.githubusercontent.com/34302354/35337542-7c960164-0156-11e8-897f-d9d37e0b055f.png)

**Comment by leonsoft-kras** [comment]
what's wrong?

**Comment by rld243** [comment]
The "Template" text box should be moved a few pixels to the right to match both "Destination folder:" and "Save as:" text boxes. It's just displaced a little.

**Comment by Dustie** [comment]
Well, now it makes perfect sense.

**Comment by AlmightyCZ** [comment]
I'm having troubles to make it work with TV series titles. I have template like this
![screen shot 2018-03-25 at 20 30 16](https://user-images.githubusercontent.com/13013656/37878585-9d8baf7e-306b-11e8-8777-09a2fbe8287c.png)
Then I:
1) Click OK for this download
2) Add another torrent with different name (it's mkv, but it shouldn't match template from the screenshot) and destination
3) Add another episode of American dad (filename is almost same se the screenshot case)
-> The American Dad folder is not preselected, there is still the last used folder from step 2
Tested with 5.15.2
Should I change something in my template syntax?

**Comment by leonsoft-kras** [comment]
Оnly the file extension is checked.
There are plans to expand the possibilities.

**Comment by AlmightyCZ** [comment]
I see, thanks for info. I was following the ToolTip example, so maybe it'd be a good thing to temporarily remove the tom*jerry example?
![screen shot 2018-03-26 at 07 20 11](https://user-images.githubusercontent.com/13013656/37888187-3ad79f22-30c6-11e8-9e54-a1fd61d95a97.png)

**Comment by leonsoft-kras** [comment]
ok thanks

**Comment by PeterDaveHello** [comment]
I think we're out of the topic here ... let's close it.
