### ISSUE TITLE
.torrent auto opening

### ISSUE THREAD

**Issue by Pusha1d** [transmission-remote-gui/transgui#1070]
Could you add the possibility of automatic download start if new .torrent file is put in the specific folder?
For example, we set some folder for .torrent files and when I put file there, the downloading starts automatically.

**Comment by dbw9580** [comment]
[https://github.com/transmission/transmission/wiki/Editing-Configuration-Files](https://github.com/transmission/transmission/wiki/Editing-Configuration-Files)
> * watch-dir: String
> * watch-dir-enabled: Boolean (default = false) Watch a directory for torrent files and add them to transmission.

**Comment by antekgla** [comment]
Well I iimplement this feature with https://github.com/transmission-remote-gui/transgui/commit/d7bff3e7bf05aee1d0a67a332ead02f54bc808e1

Now in _transgui.ini_ in the **[interface]** section you can define 3 values to watch a LOCAL folder for .torrent files

**WatchLocalFolder**= {LOCAL Folder to watch for torrent files}
**WatchDestinationFolder**= {REMOTE destination where the data would be saved if missing or empty last destination folder is used}
**WatchInterval**=1 {Time period in MINUTES between folder scans for torrents, may be fractional values 
0,50 = 30 seconds}

The only MANDATORY for watch a local folder is **WatchLocalFolder** and this folder has to exist and be writable (for delete the .torrents after adding) if the other two values are missing or empty the folder would be scanned every 1 minute and saved in the last destination used by TransGUI.

I almost sure what this works in all platforms but for security **I really need to someone test this in LINUX & MacOSX and give some feedback**.

**Comment by antekgla** [comment]
Anyone?

**Comment by antekgla** [comment]
Well I´m closing this because nobody test in other OS. 
I assume what when this got released if any error somebody would open a issue.

In the other subject i noticed what I addresed several requests from people who do not even bother writing a simple "thank you". 
Very frustrating.

**Comment by PeterDaveHello** [comment]
[v5.15.0](https://github.com/transmission-remote-gui/transgui/releases/tag/v5.15.0) released.

**Comment by theerror** [comment]
@antekgla Just looking for this feature and it's amazing, that's implemented and so sad, that no body test it on other OSs. I do have Mac as well as Ubuntu, so I can test the both. 

Just - the advanced stuff on OSX is bit tricky for me, not yet know where I should look for, so If you point me out where I can find that _transgui.ini_ will give a try.

**Comment by su30** [comment]
> Just - the advanced stuff on OSX is bit tricky for me, not yet know where I should look for, so If you point me out where I can find that _transgui.ini_ will give a try.
> ```

1. You may find transgui.ini i n hidden `config` folder of your home directory. Just open home directory and press shift+command+.
2. WatchLocalFolder = "~/Downloads" this does not work, specify full path WatchLocalFolder=/Users/user_dir/Downloads
