### ISSUE TITLE
Replace error

### ISSUE THREAD

**Issue by cociweb** [transmission-remote-gui/transgui#1071]
Hi,
Win10, V5.13:
After I pressed F6 and modified the path of the download folder and clicked ok, I got the following error:
![kep](https://user-images.githubusercontent.com/1935413/35477680-1e86a360-03c9-11e8-9157-4dae30bd133b.png)
The Move is successful, only this error is appeared.

**Comment by leonsoft-kras** [comment]
Repeat #1057
