### ISSUE TITLE
transgui.lpr(52,1) Error: Can't open resource file "(...)/transgui.res"

### ISSUE THREAD

**Issue by ghost** [transmission-remote-gui/transgui#1076]
I can't build transgui 5.14.0 because there is no transgui.res.
`make -j12 
Using Lazarus dir: /usr/share/lazarus/
/bin/mkdir -p units/x86_64-linux
/usr/share/lazarus//tools/lazres connoptions.lrs connoptions.lfm
/usr/share/lazarus//tools/lazres colsetup.lrs colsetup.lfm
/usr/share/lazarus//tools/lazres about.lrs about.lfm
/usr/share/lazarus//tools/lazres movetorrent.lrs movetorrent.lfm
connoptions.lfm/usr/share/lazarus//tools/lazres download.lrs download.lfm
 ResourceName='TConnOptionsForm' Type='FORMDATA'about.lfm ResourceName='TAboutForm' Type='FORMDATA'colsetup.lfm/usr/share/lazarus//tools/lazres options.lrs options.lfm
 ResourceName='TColSetupForm' Type='FORMDATA'movetorrent.lfm ResourceName='TMoveTorrentForm' Type='FORMDATA'
download.lfm ResourceName='TDownloadForm' Type='FORMDATA'
/usr/share/lazarus//tools/lazres baseform.lrs baseform.lfm

/usr/share/lazarus//tools/lazres main.lrs main.lfm

baseform.lfm ResourceName='TBaseForm' Type='FORMDATA'options.lfm
 ResourceName='TOptionsForm' Type='FORMDATA'
/usr/share/lazarus//tools/lazres daemonoptions.lrs daemonoptions.lfm

main.lfm/usr/share/lazarus//tools/lazres addtracker.lrs addtracker.lfm
 ResourceName='TMainForm' Type='FORMDATA'/usr/share/lazarus//tools/lazres addtorrent.lrs addtorrent.lfm
daemonoptions.lfm ResourceName='TDaemonOptionsForm' Type='FORMDATA'addtracker.lfm ResourceName='TAddTrackerForm' Type='FORMDATA'/usr/share/lazarus//tools/lazres torrprops.lrs torrprops.lfm

/usr/share/lazarus//tools/lazres addlink.lrs addlink.lfm
addtorrent.lfm ResourceName='TAddTorrentForm' Type='FORMDATA'torrprops.lfm ResourceName='TTorrPropsForm' Type='FORMDATA'
addlink.lfm ResourceName='TAddLinkForm' Type='FORMDATA'

/usr/bin/ppcx64 -MObjFPC -dLCL -dLCLgtk2 -O2 -g- -CX -XX -Xs -Fusynapse/source/lib -Fujson -Fu/usr/share/lazarus//lcl/units/x86_64-linux -Fu/usr/share/lazarus//lcl/units/x86_64-linux/gtk2 -Fu/usr/share/lazarus//components/lazutils/lib/x86_64-linux -Fu/usr/lib/fpc/3.0.4/units/x86_64-linux/rtl -FE. -FUunits/x86_64-linux -Cg -dx86_64 transgui.lpr
Free Pascal Compiler version 3.0.4 [2018/01/30] for x86_64
Copyright (c) 1993-2017 by Florian Klaempfl and others
Target OS: Linux for x86-64
Compiling transgui.lpr
Compiling baseform.pas
Compiling vargrid.pas
Compiling varlist.pas
Compiling main.pas
Compiling ./synapse/source/lib/httpsend.pas
Compiling ./synapse/source/lib/blcksock.pas
Compiling ./synapse/source/lib/synafpc.pas
Compiling ./synapse/source/lib/synsock.pas
ssfpc.inc(714,26) Warning: Symbol "HostToNet" is deprecated
ssfpc.inc(824,18) Warning: Symbol "HostToNet" is deprecated
ssfpc.inc(884,25) Warning: Symbol "NetToHost" is deprecated
Compiling ./synapse/source/lib/synautil.pas
synautil.pas(637,96) Warning: Symbol "TimeSeparator" is deprecated
synautil.pas(1981,3) Note: Local variable "BackStop" is assigned but never used
synautil.pas(2121,88) Warning: Symbol "ShortMonthNames" is deprecated
synautil.pas(2122,87) Warning: Symbol "ShortMonthNames" is deprecated
Compiling ./synapse/source/lib/synacode.pas
Compiling ./synapse/source/lib/synaip.pas
Compiling rpc.pas
Compiling ./synapse/source/lib/ssl_openssl.pas
Compiling ./synapse/source/lib/ssl_openssl_lib.pas
Compiling main.pas
Compiling ipresolver.pas
Compiling GeoIP.pas
Compiling utils.pas
utils.pas(313,46) Warning: Symbol "Create" is deprecated: "Use Options argument instead"
utils.pas(507,56) Warning: Implicit string type conversion with potential data loss from "UnicodeString" to "AnsiString"
utils.pas(507,40) Warning: Implicit string type conversion with potential data loss from "UnicodeString" to "AnsiString"
Compiling restranslator.pas
Compiling addtorrent.pas
Compiling main.pas
Compiling StringToVK.pas
Compiling connoptions.pas
Writing Resource String Table file: connoptions.rsj
Compiling torrprops.pas
Compiling daemonoptions.pas
Writing Resource String Table file: daemonoptions.rsj
Compiling about.pas
Writing Resource String Table file: about.rsj
Compiling download.pas
Writing Resource String Table file: download.rsj
Compiling colsetup.pas
Compiling addlink.pas
Writing Resource String Table file: addlink.rsj
Compiling movetorrent.pas
movetorrent.pas(81,5) Note: Local variable "c" not used
movetorrent.pas(81,7) Note: Local variable "c1" not used
movetorrent.pas(81,10) Note: Local variable "c2" not used
Writing Resource String Table file: movetorrent.rsj
Compiling addtracker.pas
Writing Resource String Table file: addtracker.rsj
Compiling options.pas
Compiling bencode.pas
main.pas(1160,10) Warning: Comparison might be always true due to range of constant and expression
main.pas(1401,3) Note: Local variable "MI" not used
main.pas(1401,7) Note: Local variable "MI2" not used
main.pas(1402,3) Note: Local variable "Ico" not used
main.pas(1403,3) Note: Local variable "LargeIco" not used
main.pas(1403,13) Note: Local variable "SmallIco" not used
main.pas(1404,3) Note: Local variable "MenuCaption" not used
main.pas(3817,64) Warning: Implicit string type conversion with potential data loss from "UnicodeString" to "AnsiString"
main.pas(5276,3) Note: Local variable "l_old" is assigned but never used
main.pas(5325,10) Warning: Implicit string type conversion from "UTF8String" to "WideString"
main.pas(5333,16) Warning: Implicit string type conversion from "UTF8String" to "WideString"
Writing Resource String Table file: main.rsj
addtorrent.pas(830,57) Warning: Implicit string type conversion with potential data loss from "WideString" to "AnsiString"
addtorrent.pas(1035,5) Note: Local variable "min" not used
addtorrent.pas(1035,9) Note: Local variable "max" not used
addtorrent.pas(1035,13) Note: Local variable "indx" not used
addtorrent.pas(1035,19) Note: Local variable "fldr" not used
addtorrent.pas(1036,3) Note: Local variable "pFD" not used
Writing Resource String Table file: addtorrent.rsj
rpc.pas(742,46) Warning: Symbol "Create" is deprecated: "use options form instead"
Writing Resource String Table file: rpc.rsj
transgui.lpr(52,1) Error: Can't open resource file "/var/tmp/portage/net-p2p/transmission-remote-gui-5.14.0/work/transmission-remote-gui-5.14.0/transgui.res"
transgui.lpr(52,1) Fatal: There were 1 errors compiling module, stopping
Fatal: Compilation aborted
make: *** [Makefile:1932: transgui] Error 1

**Comment by leonsoft-kras** [comment]
someone deleted the transgui.res file from the project.
I don't know why this was done.

**Comment by rzcat** [comment]
try modifying the exe icon or any action that would generate that res file
