### ISSUE TITLE
file VERSION.txt

### ISSUE THREAD

**Issue by leonsoft-kras** [transmission-remote-gui/transgui#1081]
Why in version 3 numbers?
at the moment 5.14.0, not 5.14

**Comment by antekgla** [comment]
I think what is from the original code.
The base code for this is 5.0.1

**Comment by leonsoft-kras** [comment]
We have only used 2 digits for a long time.
I suggest writing a version like 5.14

The first digit is the main version.
The second digit - any changes in the main version.

**Comment by PeterDaveHello** [comment]
Maybe we can use semantic versioning, much more meaningful, reference: https://semver.org/

**Comment by leonsoft-kras** [comment]
In the world there are many models of numbering versions. Everyone proves that his best. Only the user is interested in changing the number (letter) and he used the latest version. You can make at least 6 digits. This is a useless work from the point of view of the average user.
So I left version 5, the 2nd digit is the modification of the program.

So, are you able to define the line between MINOR and PATH version?

**Comment by PeterDaveHello** [comment]
For the releases contain bug fixes only, use patch version, with features, use minor version.
