### ISSUE TITLE
Application crash when met with illegal file name (containing colon)

### ISSUE THREAD

**Issue by stevenlele** [transmission-remote-gui/transgui#1084]
TRGUI 5.14, Windows 10 x64 (1709)

The GUI crashes when adding torrents or selecting torrents containing file name with ":" (colon).

Example: https://nyaa.si/view/1009219

**Comment by leonsoft-kras** [comment]
yes, there is a problem

**Comment by leonsoft-kras** [comment]
I put a patch in the author's code for the symbol ":".
In general, this is initially a problem with a bad file name in the torrent.
