### ISSUE TITLE
 Please add a "Checking" in the category

### ISSUE THREAD

**Issue by Gokou-Ruri** [transmission-remote-gui/transgui#1088]
It is very inconvenient when a large number of Torrent are being checked.

![2018-03-02_231600](https://user-images.githubusercontent.com/26711804/36906304-8787b7b6-1e70-11e8-93b5-33e65ff0269c.png)
![2018-03-02_231624](https://user-images.githubusercontent.com/26711804/36906305-87c0ae2c-1e70-11e8-9d76-279470e315f1.png)

**Comment by antekgla** [comment]
View #1089
