### ISSUE TITLE
New feature: Filter by Waiting Category

### ISSUE THREAD

**Issue by antekgla** [transmission-remote-gui/transgui#1089]
Partially in response to #1088 I added a new Filter category: **Waiting** https://github.com/transmission-remote-gui/transgui/commit/6e191278f50f944b58da3357411470f7d1303aec

This new category affect to all torrents with the following states:

- Verifying
- Waiting to Verify
- Waiting to Download

![filter waiting 3](https://user-images.githubusercontent.com/24402722/36940570-30fddf92-1f24-11e8-83d4-10ff551fb659.jpg)

When you exceed the number of torrents to download set in **Download Queue** that torrents are in state **Waiting to Download**. To now there is not a way to view that torrents in a clear way. Now you can click in Waiting Filter and only that torrents are displayed.

A new keyboard shortcut is added to this category: Alt+8

In addition and in response to #1088 when you verify more of one torrent the first is verified and the other are set to **Waiting to Verify** state. That two states are displayed in this filter too.

**Note** what the torrents in **Waiting to Seed** state are NOT filter with this new Category.

**Comment by PeterDaveHello** [comment]
[v5.15.0](https://github.com/transmission-remote-gui/transgui/releases/tag/v5.15.0) released.

**Comment by cryodream** [comment]
Thank You, thank You, thank You.
Been waiting for this for years.
