### ISSUE TITLE
Adding torrent link by hash

### ISSUE THREAD

**Issue by ploink** [transmission-remote-gui/transgui#1090]
Adding a torrent link by hash is supported by the transmission web client and it would be very useful as some torrent sites publish the hash but require login to get the torrent.
https://forum.transmissionbt.com/viewtopic.php?t=13000

For example just press ctrl-ins and paste b13e23c89a3b31dca82fd2739b2445e389986b8b to download Fedora-Workstation-Live-x86_64-27
Current version just throws an "unable to open file" error.

Implementation should be easy: 
If input identified as a hash then convert to magnet link and submit.
magnet:?xt=urn:btih:b13e23c89a3b31dca82fd2739b2445e389986b8b

**Comment by antekgla** [comment]
I'm using torrents for several years and never see a site like you say. 
It is a private tracker?
What site is?

**Comment by leonsoft-kras** [comment]
Yes, it can be done in principle. If the link does not contain the word "magnet:? Xt", then automatically add it.

**Comment by ploink** [comment]
@antekgla: Thank you for the quick implementation!

The website that prompted me for a free login to get the torrent is https://kickasstorrents.to/ and obviously I won't do that.
The site may be a fake, but it did give me the hash I needed.

**Comment by cfpp2p** [comment]
@ploink 
sites like http://thetorrent.org/ , http://btcache.me/ and http://itorrents.org/
these can be integrated https://github.com/cfpp2p/transmission/blob/master/web-client-cfp/advanced/javascript/remote.js#L242 and result in a .torrent download directly.

**Comment by PeterDaveHello** [comment]
v5.15.0 coming.
@antekgla I wonder maybe we could close issue once it's implemented?

**Comment by PeterDaveHello** [comment]
[v5.15.0](https://github.com/transmission-remote-gui/transgui/releases/tag/v5.15.0) released.
