### ISSUE TITLE
CPU usage and general app slowdown

### ISSUE THREAD

**Issue by peaveyman** [transmission-remote-gui/transgui#1095]
I am running this transgui using this arch linux package: https://aur.archlinux.org/packages/transgui-qt/

I have noticed a big slow down in the app. When I click to switch torrents that I am viewing it takes several seconds for the selection to change. When I set the data refresh interval in the application options to less than 5 seconds there is a big jump in cpu usage and the temp on the cpu will ramp up. It's been doing this for a while and I don't know what the problem is. If I try to run this version of the app: 
https://aur.archlinux.org/packages/transmission-remote-gui-bin/ the renaming problem pops up, ie the cursor jumping places when you backspace or use the delete key.

**Comment by leonsoft-kras** [comment]
Your transmission at this time performs downloads/uploads torrents? unlimited speed?
if this is true, then do you think that transmission is free and does not share information about his work TR GUI? 

Try setting the speed  of download / upload of torrents at the level of 1000-5000 KB/s. 
Data display is 15/60 seconds.

**Comment by leonsoft-kras** [comment]
Try to issue #1007 (Network settings)

**Comment by peaveyman** [comment]
I will give this a try when I get home.

**Comment by peaveyman** [comment]
This seems to be worse when I sort by last active. If I sort by last added it seems to calm down some. But I am sitting here now with 2500 torrents loaded and it is revving my cpu up while I am sorting by last active. I have the data refresh rate set at 5 seconds.

**Comment by peaveyman** [comment]
This is still a problem for me on linux. When I change views it takes several seconds for it to change. And when I sort by last active I have a noticeable rise in the cpu usage and cpu temp. Something is still not right with the app.

**Comment by leonsoft-kras** [comment]
1. Does transmission work at this time? yes / no
2. Does the TRG execution change when transmission is turned on and off? yes / no
3. How does the execution of TRG change? _____

**Comment by peaveyman** [comment]
Yes, transmission works. I'm not sure what you mean by the 2nd and 3rd questions.

**Comment by leonsoft-kras** [comment]
2. Stop transmission. Is there a problem with TRG?
3. Describe the problem (see item 2)

**Comment by peaveyman** [comment]
I stopped transmission. TRG of course doesn't work because transmission isn't there for it to connect to. I can switch from the General tab to the tracker tab and the rest of the tabs. That's not the problem. The problem is that when TRG is connected to transmission and I try to select different torrents to look at the details or when I have all torrents selected in the left side panel and go to the active or downloading or complete selection it takes several seconds for it to switch to the selection. And when I have the torrents sorted by last active the CPU usage goes way up for TRG.

**Comment by peaveyman** [comment]
It works as expected in turtle mode. The tabs do display a little quicker. The process moves from 0% to 15 or 25% and then back to 0.

**Comment by leonsoft-kras** [comment]
TRG constantly turns to the transmission to display your data (torrents). To prepare data, the transmission spends its resources. If there is a lot of data, then this affects the network exchange. The amount of data obtained depends on the performance of the TRG.

When the transmission is busy (downloading and distributing torrents), then it does not have enough resources to prepare and transfer data to the network. Network exchange is very slow. 

TRG is a single-threaded application. Getting on the network and displaying data depend on each other.

Stop the work of the transmission to work with the TRG. 
Another option is to set a limit on downloading and distributing torrents (Transmiss option-global bandwidth speed).
