### ISSUE TITLE
Windows version of .15?

### ISSUE THREAD

**Issue by madgabz** [transmission-remote-gui/transgui#1100]
Where to download the new version for windows? Or, hasn't it been compiled and packaged yet?
Sincerely,
MadGabZ

**Comment by PeterDaveHello** [comment]
As we don't have automatic build for Windows, it takes more time and manual works to have Windows release. We just released the Windows package a few hours ago. Download it here:
- https://github.com/transmission-remote-gui/transgui/releases/tag/v5.15.0
  - https://github.com/transmission-remote-gui/transgui/releases/download/v5.15.0/transgui-5.15.0-i386-win32.zip
  - https://github.com/transmission-remote-gui/transgui/releases/download/v5.15.0/transgui-5.15-setup.exe
