### ISSUE TITLE
I can't update the GeoIP

### ISSUE THREAD

**Issue by Gokou-Ruri** [transmission-remote-gui/transgui#1103]
Windows 10 14393 x64
TransGUI v5.15.2

![2018-03-24_193508](https://user-images.githubusercontent.com/26711804/37863556-b35f8db0-2f9a-11e8-900f-21251939e9a2.png)

**Comment by PeterDaveHello** [comment]
@Gokou-Ruri Operating System version, application version please ...

**Comment by PeterDaveHello** [comment]
@Gokou-Ruri can you please confirm if you can properly download this file by a browser?
http://geolite.maxmind.com/download/geoip/database/GeoLiteCountry/GeoIP.dat.gz

**Comment by Gokou-Ruri** [comment]
@PeterDaveHello Yes, I can download it.

**Comment by Gokou-Ruri** [comment]
@PeterDaveHello Thank you, But I can't download this file. 
`{"success":false,"error":404,"message":"Not Found"}`

**Comment by PeterDaveHello** [comment]
@Gokou-Ruri seems to be downloded by someone else, give me few mins, I'll directly upload on GitHub.

**Comment by Gokou-Ruri** [comment]
@PeterDaveHello Great! I can update with this version.

**Comment by PeterDaveHello** [comment]
@Gokou-Ruri cool, I'll commit this change to the master branch, you can use this download right now.

**Comment by PeterDaveHello** [comment]
https://github.com/transmission-remote-gui/transgui/releases/tag/v5.15.3
