### ISSUE TITLE
Mac Access Violation to eventual pinwheel death crash

### ISSUE THREAD

**Issue by sarossell** [transmission-remote-gui/transgui#1105]
Great program! Just having some trouble with Access Violation Errors.
MacBook Pro - High Sierra 10.13.3 / Transgui 5.15.2 / Catch 1.9.4
Magnets load consistently (sometimes only one. Sometimes up to four) until a first Access Violation error, then subsequent attempts to load different magnets result in Access Violation errors eventually leading to a pinwheel of death crash.
Force quit and rerun of Transgui returns functionality.

**Comment by PeterDaveHello** [comment]
@sarossell is this problem only appears at v5.15.2? There may be an issue reporting this problem before if I didn't remember it wrong :)

**Comment by sarossell** [comment]
I've had this same issue since I first heard of the program at version 5.13. I search for similar issues, but found nothing. Apologize if I missed it.

**Comment by sarossell** [comment]
UPDATE: I decided to try a different method of installation in the off chance that a dependency was missed. I removed all traces of the app installed from DMG and instead installed from Brew. It seems to be working much better now. I love this program! Thanks for all your all hard work.

**Comment by PeterDaveHello** [comment]
@sarossell actually the brew installatoin is doing the same thing to install from a dmg image, but we developers here barely use MacOS so haven't had a deep look at it yet ...

**Comment by sarossell** [comment]
I love this program...when it works. Still having the same issues; Access violation, timeout, pinwheel of death, etc. I'm running v5.15.4 Mac from Brew install. I  had earlier tried the dmg installs, but you indicated there was no difference and that has sadly proven true in my case. Oddly, the errors I get seem to come most often with newer magnet links. Once they're about a day old, they seem to load just fine. I can always eventually get a link to start downloading after closing and restarting the app a few times or resorting to a torrent file instead of magnet a few times.

**Comment by PeterDaveHello** [comment]
@sarossell yeah, I understand, we need more developers here to help :)

**Comment by sarossell** [comment]
I understand. Thank you. If it's any help at all, it seems that only very new magnet links are affected. Older links appear to work flawlessly. I don't know enough about magnet files, but there must be some bit of data that changes over time(?)

Still, great program. Saves me tons of time. Thanks!

**Comment by sarossell** [comment]
Oops. Actually, after further testing (and researching what a magnet link is), I've determined I was completely wrong. The "age" of the link is immaterial. The error I get most often is "Access Violation", but access to what? A database? Is it running out of memory? Or pointing at some incorrect index? 

Maybe the attached crash report will help.

[Mac Crash Report.txt](https://github.com/transmission-remote-gui/transgui/files/1964962/Mac.Crash.Report.txt)

**Comment by antekgla** [comment]
How you add the magnet links?
Clipboard or Button (Add Magnet Link)?

Please check TransGUI 5.14.0... That version give you the same errors?

**Comment by antekgla** [comment]
From 5.15.0 is possible to add magnets only by hash... and that routine brought some trouble in the first version. I fix that in 5.15.2.

**Comment by sarossell** [comment]
Ah, interesting. Thank you for that information. Over the past 24 hours, I've had much better functionality since I unchecked those options in Settings. However, one error still persists. If the program is not currently running when a magnet link is activated, the Mac automatically runs TransGUI, but then just spins the pinwheel of death until finally reporting a timeout error. This only occurs upon initial startup of the app from an associated link activation. So, I just leave it running. But then it takes up valuable space on my Dock. I have the tray icon as well, but the only way to remove the doc icon is to Exit the program. Then it's not running of course. I tried to select "Minimize to tray", but the checkbox is disabled. I tried selecting "Close to tray", but that didn't work either.

By the way, the "Quit Transmission Remote GUI" menu option doesn't work. The shortcut CMD+Q does though.  And the Exit option and shortcut (Alt-X) under Torrent in the menu works as well.

**Comment by antekgla** [comment]
Where you have Transmission running? (Transmission not TransGUI)
In a remote server or locally?
If you have Transmission running locally you may associate magnets with Transmission instead TransGUI. That way anytime Catch runs a magnet link TransGUI is not executed.

**Comment by sarossell** [comment]
I appreciate the advice, but I run Transmission on a remote Linux server across town with much better bandwidth and then connect to it with TransGUI on my Mac.
