### ISSUE TITLE
OpenSSL for Windows v1.0.2o

### ISSUE THREAD

**Issue by cfpp2p** [transmission-remote-gui/transgui#1110]
operating system: XP sp2
Transmission Remote GUI version: 5.15.3 installer .exe

`Entry Point Not Found` dialog before Transmission Remote GUI then starts correctly.
 OpenSSL for Windows v1.0.2n functions correctly.
XP sp2, It's an old test box.

**Comment by leonsoft-kras** [comment]
32 / 64 bit - for XP and TRGUI ?

**Comment by cfpp2p** [comment]
32 bit both

**Comment by PeterDaveHello** [comment]
Wow, serious Win XP SP2? Do you have SP3?

**Comment by cfpp2p** [comment]
@PeterDaveHello   I tested now with SP3 and it loads the .DLL s but immediate crash results. Perhaps we shouldn't load the .DLL s unless **_use SSL_** is checked but I really don't think putting any time into this is worth the trouble.

**Comment by PeterDaveHello** [comment]
Yes, WinXP is dated for a long long time.
