### ISSUE TITLE
Error when changing file location LS-002

### ISSUE THREAD

**Issue by xruyn** [transmission-remote-gui/transgui#1111]
Hi! 
TransDaemon are installed in Ubuntu Server 16.04. TRG v.5.15.3 used in Windows 10, Ubuntu 16.04, Mint 18. 
When manually changing a torrent's file location, I get the following error:
![2018-04-02 17 07 21](https://user-images.githubusercontent.com/22565406/38299271-3999500e-3802-11e8-81d4-5c04c2a03cca.jpeg)

But it still changes the file's location and torrent started download. 
Some addition. I corrected the icons with Lazarus. But the compilation was successful. I do not think that this is the case.

**Comment by leonsoft-kras** [comment]
fixed the error (missed the previous edits) 
:(

**Comment by PeterDaveHello** [comment]
https://github.com/transmission-remote-gui/transgui/releases/tag/v5.14.4
