### ISSUE TITLE
Move source files in a subfolder, making the readme files more visible to users

### ISSUE THREAD

**Issue by Diskutant** [transmission-remote-gui/transgui#1117]
I think it would be a good idea to make the ReadMe files more visible to users on the GitHub Page, and make the GitHub page more clean, so the ReadMe file at the bottom is easier to reach and see for users.
I think this will make an much better impression to new users and new developers.

I already made the neccessary changes.
I updated and tested the mac build script, that works for me. I updated the windows script, but can't test it. The unix script might need an update to reflect the changes, but I didn't fully understand it.

The pull request is here: https://github.com/transmission-remote-gui/transgui/pull/1116
But PeterDaveHello told me to open a discussion here instead.

**Comment by PeterDaveHello** [comment]
@Diskutant the concept is good, however itn't a good idea to touch something you don't even know and you don't even test, in the PR, you touched too many things, for example, the .travis.yml, I against doing this too rough.

**Comment by Diskutant** [comment]
Well, the idea was to move the source root folder into the src folder, and just keep the user readable files next to it. That would mean the least changes to scripts. Those readme files are used in the scripts though, so the path had to be changed in there. If the .travis.yml needs to be in project root for some reason, I can move it back there, but that would mean changes in the travis file because now the relative paths from there would change.

**Comment by leonsoft-kras** [comment]
I suggest closing the issue. Honestly, I do not understand many empty body movements. 

I found all the files in my time, compiled the code right away and began to modify it. No problem that the files are located somehow wrong. They are always so placed and no one experienced problems))

**Comment by Diskutant** [comment]
The problem isn't to find the files. The problem is the github page (https://github.com/transmission-remote-gui/transgui) looks like a mess.
Especially for end users it's better to make the ReadMe more visible on that page. And that's done by not having a laughable large file list in front of it.
