### ISSUE TITLE
32-bit app compatibility with macOS High Sierra

### ISSUE THREAD

**Issue by reedy** [transmission-remote-gui/transgui#1122]
Apple are starting giving warnings about https://support.apple.com/en-gb/HT208436

**Comment by PeterDaveHello** [comment]
AKAIK, none of our core members has a Mac computer right now, pull requests would be welcome.

**Comment by PeterDaveHello** [comment]
@xiao99xiao we have some scripts under setup directory that you can try ;) You also need to know a little bit about FPC and Lazarus

**Comment by Diskutant** [comment]
@xiao99xiao No, Transgui uses the Carbon Widgets. Those are 32bit only. The Transgui Code needs to be updated to either use Cocoa (which is still a work in progress, see: http://wiki.freepascal.org/Roadmap#Status_of_features_on_each_widgetset ) or use QT widgets, which in turn uses Cocoa.

**Comment by mrowlinson** [comment]
How difficult is it to switch to Qt? Presumably the Linux version is already using Qt? The rumor is Apple is going to remove the 32 bit libraries from the next version of macOS so unless the transition is made the app will cease to function.

**Comment by mrowlinson** [comment]
Why was this closed?

**Comment by leonsoft-kras** [comment]
The question can be considered dead. There are dozens of such topics. No one will look at them in the coming days and years. Especially here there are certainly no experts on strange macOS. There is nowhere to check it.


It's better to close the topic and create a new one with the new data

**Comment by PeterDaveHello** [comment]
Let's move to #1150 for further discussion ;)
