### ISSUE TITLE
runtime error 200

### ISSUE THREAD

**Issue by Nchalada** [transmission-remote-gui/transgui#1124]
OS: Win 10 Pro x64
Daemon: 2.92 on Win 7 x64
GUI: 5.15.4 

![](https://i.imgur.com/EZzOwNK.png)

Doesn't seem to matter what I do, I constantly get this error.
I've reinstalled. rebooted everything, etcetc

**Comment by leonsoft-kras** [comment]
little information on the causes of the failure :(
