### ISSUE TITLE
sourceforge project should be closed or redirect to github

### ISSUE THREAD

**Issue by Jimbolino** [transmission-remote-gui/transgui#1126]
untill today the first hit in google is the sourceforge project page:
https://sourceforge.net/projects/transgui/

I think a lot of users, including me, are still using the old version because nowhere does it mention this github.

**Comment by PeterDaveHello** [comment]
I'm not sure if @leonsoft-kras has permission on that?

**Comment by leonsoft-kras** [comment]
I don't know how to make this version in Google first.

We have no relation to the version of sourceforge project. 
This version is accompanied by the author of the program (Yuri Sidorov, as far as I understand).

**Comment by Jimbolino** [comment]
So Yuri Sidorov is the original creater, owner of the sourceforge page, but is not affiliated with the project anymore?

**Comment by mauromol** [comment]
The README file of this repo says:
"Copyright (c) 2008-2019 by Yury Sidorov and Transmission Remote GUI working group"

The project name here is Transmission Remote GUI. So, this does not sound like a fork, but rather like the continuation of the original project. If this is a fork, not endorsed by the original author, I think it should be called in some other way, to avoid confusion.

**Comment by ibex-are-goats** [comment]
> We have no relation to the version of sourceforge project.
> This version is accompanied by the author of the program (Yuri Sidorov, as far as I understand).

What's the update on this? Are we just copying the original project including the name and the copyright??

**Comment by PeterDaveHello** [comment]
@ibex-are-goats It’s called “fork” I think, just try to continue its development
