### ISSUE TITLE
http 404 error when checking for new version (5.15.4)

### ISSUE THREAD

**Issue by panfren** [transmission-remote-gui/transgui#1129]
Windows 10 64-bit
transmission-cli 2.93 running on the local LAN
Remote GUI v. 5.15.4 (latest)
![shot5](https://user-images.githubusercontent.com/35025513/39092021-50790fdc-460b-11e8-9aa8-055cc9696ce1.png)

**Comment by Laotseu** [comment]
I've installed 5.15.4 at least a week ago and I didn't get the error message until today. Seems like a site problem, not a code problem.

Cheers.

**Comment by PeterDaveHello** [comment]
I'll take a look, thanks.
