### ISSUE TITLE
Transmission Remote gui won't quit in OSX

### ISSUE THREAD

**Issue by damiankitai** [transmission-remote-gui/transgui#1136]
even when I go to the app an quit from the menu, or use the command q shortcut, the app doesn't quit. Only force quit closes the transmission remote. 

1. Operating system
OSX 10.13.4
2. Transmission Deamon
2.92 (14714)
3. Transmission Remote GUI
5.15.4

**Comment by damiankitai** [comment]
Just realized it also quits fine from the exit menu in the icon on the upper right section. However, it should work as any app in osx and quit from the quit menu under the name of the program.

**Comment by ps2wiz** [comment]
It's not a problem, it's setting you can change.

"Tools" - Applications Options" - "Advanced" tab - uncheck "Close to tray".
