### ISSUE TITLE
Bonjour/zeroconf `.local` hostnames do not resolve

### ISSUE THREAD

**Issue by b-** [transmission-remote-gui/transgui#1137]
Operating system: macOS 10.13.5 developer beta (which uses [mDNSResponder](https://opensource.apple.com/tarballs/mDNSResponder/) to provide zeroconf services)
Remote GUI version: 5.15.4
Transmission daemon version: N/A (the GUI does not get to the daemon in the first place)

I have not tested this with [Avahi](https://github.com/lathiat/avahi) or any other Bonjour/zeroconf service, but as far as I understand *mDNSResponder* is sort of the "gold standard," anyway.

Regardless, I think this means that `transgui` is not using something like `gethostbyname` for DNS lookups on macOS, when as far as I understand it really *should*.

**Comment by barbequesauce** [comment]
That certainly explains the behavior on #1127...

**Comment by b-** [comment]
Agreed, this issue and #1127 are still not fixed. Please reopen, or add a “wontfix” label with an explanation. I don’t want to run a full DNS server on my network just for Transmission.

**Comment by leonsoft-kras** [comment]
I will explain "why" = a dead theme. From the experience of past problems there are no programmers for macos.

**Comment by b-** [comment]
The difference here is that bonjour/zeroconf is platform-agnostic. 

Most modern Linux distros come with Avahi or similar, and Windows 10 has basic support built-in, and there are better support libraries available for free from Apple (and installed automatically when you install either iTunes or certain name-brand printers.

As you probably can imagine, my Raspberry Pi (where my Transmission daemon is hosted) is running neither macOS nor a variant of Darwin — I’m using libraries that came with it to be able to call it by name.

But I’m ranting. Really, what I’m trying to say is that this isn’t a “Mac issue” except for the fact that Apple created the name resolution protocol in question.

 The issue is that transmission-remote-GUI (or rather its network library) has its own name resolution functions built-in, which means that it ignores additions such as bonjour that hook into the OS name resolution. 

THAT DOES NOT MEAN THAT THIS IS ONLY THE NETWORK LIBRARY’S PROBLEM, EITHER.

Calling the standard name resolution APIs in the OS is relatively easy, and need not be reinvented through a library. Transmission-remote-GUI can certainly add its own name-resolution function, passing things to the OS. 

By the way, I’d like to mention… I’m not certain on how name resolution traditionally works on Linux, but I’ve seen quite a few layers on top of it and not just multicast DNS. I’m curious how well (or not) this application works in that case...

**Comment by leonsoft-kras** [comment]
I know it. We are waiting for the solution of the problem.

**Comment by PeterDaveHello** [comment]
Let's move to #1127, thanks for the feedback and discussion here.
