### ISSUE TITLE
Method name not recognized/time out error when adding any torrent.

### ISSUE THREAD

**Issue by XOIIO** [transmission-remote-gui/transgui#1138]
Hello all, so I've set up transmission on my windows server, with the remote ui running on a windows machine.

The problem I have is that every single time I add a torrent, transmission does nothing for a good 10-15 seconds, then spits out either a timed out error and fails completely, or will say "no method name" in a popup and fail, or sometimes, give the no method name error, but then have the window to choose the directory and hit "ok" and add the torrent behind it, which will work.

I'm completely stumped as to this issue, there shouldn't be any connection problems since I'm just doing this on my lan, and neither machine is being hit with a lot of bandwidth, and it does this every time.

I have server 2012 R2 running on the server side, and Windows 10 on the remote ui side, all running 2.93.

If there are system logs or something I can provide to help troubleshoot just let me know where to look.

**Comment by XOIIO** [comment]
Well, this issue seems to have resolved itself.

**Comment by iSLC** [comment]
I've encountered this a few times myself. It just happens randomly. It only happened with magnet URLs tho. To get it working I just have to use the actual torrent file. Eventually I have to restart the application or it just stays stuck and does that for all magnet URLs and not just that particular one which caused the message to pop up.

**Comment by xorinzor** [comment]
I have this issue too and noticed that it seems to happen when I add a torrent whenever it's refreshing it's data. If I add a torrent just after it has refreshed it's usually fine.

**Comment by xorinzor** [comment]
@leonsoft-kras has this been fixed? I can't find a commit about it

**Comment by leonsoft-kras** [comment]
see above - 2nd message: Well, this issue seems to have resolved itself.

**Comment by xorinzor** [comment]
For him maybe, yes. But the issue was still present for me.
The only workaround I found was to add a torrent quickly after I saw it updated.

As soon as it's trying to update while I'm adding a torrent everything just freezes up.

**Comment by leonsoft-kras** [comment]
**To eliminate the error, the programmer must repeat it at home.**

I dont understand what's going on. What you use the settings of the program, etc.?
What is your operating system, version of the programs?
Did you try other versions of the programs, including the transmission?

Not enough information. Perhaps you are the only one who has such a problem.
