### ISSUE TITLE
SSL/TLS Support not compiled

### ISSUE THREAD

**Issue by lampra1** [transmission-remote-gui/transgui#1139]
1. Operating system: Ubuntu 18.04 64bit clean installation, 
1.1. Openssl version: OpenSSL 1.1.0g  2 Nov 2017
2. Transmission Deamon: 2.92 (on Debian stretch openssl version OpenSSL 1.1.0f  25 May 2017)
3. Transmission Remote GUI: 5.15.4
![transgui](https://user-images.githubusercontent.com/31213906/39678761-149d4be0-519b-11e8-83f4-7ab0cbc1eafa.png)
This was installed from the tarball not compiled from source. Do I need to compile it myself?
On a windows machine geoip database is well updated.

**Comment by lampra1** [comment]
Based on this [http://forum.lazarus-ide.org/index.php?topic=25232.0](url) after the installation of libssl-dev package problem is solved.

**Comment by nelsonblaha** [comment]
I'm getting this in Ubuntu 22.04.1 despite having libssl-dev
