### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by nibbles-** [transmission-remote-gui/transgui#1140]
1. Operating system: Win10 x64
2. Transmission Deamon 2.92 Debian Stable
3. Transmission Remote GUI 5.15.4

Lately I have started to get this.
![image](https://user-images.githubusercontent.com/10529502/39750535-c3a7889c-52b5-11e8-9cf8-d80ea4c20bd5.png)

It seems that the issue occurs when I mouse over the "Added On" column.
Transgui then tries to add a torrent (could be from clipboard) but since there is nothing there.
All collumns are empty and after a few seconds it crashes with the screenshot error message

**Comment by leonsoft-kras** [comment]
I can't repeat your situation.
If the situation repeats, describe the detailed actions and the initial data.

**Comment by nibbles-** [comment]
If I start it with an empty torrentlist (ie no torrents added) and then mouse over the list (the part of the window which is a listview) the top line will get selected just as if it where a torrent in the list.
If I then click around in the window or at the selected line the program crashes. Sometimes with the above error message sometime without anything

**Comment by nibbles-** [comment]
crashed a few times on startup. then the same as before.
different error (address) though
![image](https://user-images.githubusercontent.com/10529502/42133045-75b9be50-7d23-11e8-808b-378ba97ee662.png)

**Comment by nibbles-** [comment]
a reinstall seems to have fixed it.

**Comment by leonsoft-kras** [comment]
![default](https://user-images.githubusercontent.com/11468577/42133423-1e4af9aa-7d54-11e8-96e8-9d75511d51a8.png)
The screen was such before failure?

**Comment by nibbles-** [comment]
Yes! Except I dont have the filter pane visible

**Comment by leonsoft-kras** [comment]
[transgui.zip](https://github.com/transmission-remote-gui/transgui/files/2152761/transgui.zip)
try it

**Comment by nibbles-** [comment]
Seems to work.

**Comment by leonsoft-kras** [comment]
strange problem. sometimes there is an empty line of the torrent.
then there is an error in determining the size of the torrent (nonexistent).

The reason for the appearance of a random blank line is unknown to me (almost impossible to determine).
