### ISSUE TITLE
FromNow format - incorrect counting

### ISSUE THREAD

**Issue by pasha-zzz** [transmission-remote-gui/transgui#1141]
v5.15.4, when date/time (f.e. added) is, f.e. 22:00 1st day and now is 00:20 2nd day - it shows 1d 2h. But only 2h 20min elapsed. Maybe depends from timezone (my is GMT+3)

**Comment by antekgla** [comment]
Yeah it is a bug...
It is solved in https://github.com/transmission-remote-gui/transgui/commit/59c594667c87080279d364645b25b640050b54d7
Would be included in the next release.

**Comment by pasha-zzz** [comment]
Bug in PeriodBetween function?

**Comment by antekgla** [comment]
> Bug in PeriodBetween function?

I dont know, maybe... technically day is different however it is true what is only 2hs 20min of difference.

**Comment by pasha-zzz** [comment]
Maybe check this too "22:00 1st day - 00:20 3rd day"? Must be 1d 2h, not 2d 2h

**Comment by pasha-zzz** [comment]
I think this correction:
`if HoursBetween(Anow,AThen) < 24 then Days := 0;`
we can replace with this:
`if CompareTime(Anow,AThen) < 0 then Dec(Days);`

**Comment by pasha-zzz** [comment]
Additional check needed for other date/time components in PeridBetween. Maybe if Day(Anow)<Day(Athen) - decrease of Month is needed. And same for Month numbers which affect Year

**Comment by pasha-zzz** [comment]
![default](https://user-images.githubusercontent.com/8224786/39888633-0cc71fe4-549e-11e8-9582-b23e3d46e940.png)
Period between datetimes - 1 day and 1 second.

**Comment by antekgla** [comment]
:smile:

We think the same...

![periodbetween](https://user-images.githubusercontent.com/24402722/39896425-6d01b2da-5484-11e8-98dc-5b637a73e59b.jpg)

**Comment by pasha-zzz** [comment]
Tested other components of datetime, only Days are affected. Months and Years are always correct. But PeriodBetween flips values if they are in reversed order. And my final correction for Days is:
`if Sign(Anow-Athen)*CompareTime(Anow,Athen) < 0 then Dec(Days);`

**Comment by antekgla** [comment]
Thank you for your work in this...
However I can't imagine a case where **Athen** would be older what **Anow**, except maybe if you change the clock in your computer to a earlier day/hour.
In every case in real world use **Anow** would be always older what **Athen**.

When we call the function 
```pascal
HumanReadableTime(ANow,AThen: TDateTime): string;
```
the first parameter is the function **Now** what return the current day/hour so that value would be always older what AThen.

**Comment by pasha-zzz** [comment]
Yes, but incorrect datetime possible not only on user side but on the torrents creator side f.e. Additional check not so time consuming I think

**Comment by antekgla** [comment]
Fix (definitely I hope) in https://github.com/transmission-remote-gui/transgui/commit/c8e84bd1a1109a18270e598d419a3241654dc9fe
Thanks @pasha-zzz !!!!
