### ISSUE TITLE
DOUBT: RWindows: Where are the column settings saved?

### ISSUE THREAD

**Issue by SouzaRM** [transmission-remote-gui/transgui#1144]
REASON: I'd like to take the whole app on the pen-drive.

I already ran the program TRANSGUI with [SYSInternals: ProcessMonitor] and could not identify.

Thank you!

[RWin7 x64]

**Comment by PeterDaveHello** [comment]
@SouzaRM "AppData\Local\Transmission Remote GUI" under user's home directory, for example:
C:\Users\Peter\AppData\Local\Transmission Remote GUI

**Comment by SouzaRM** [comment]
Thanks @PeterDaveHello,

But my Rwindows 7 x64 don't restore correct!

Vide [Columns setup not save when relaunching Transmission GUI #273]
[https://github.com/transmission-remote-gui/transgui/issues/273]

**Comment by PeterDaveHello** [comment]
@SouzaRM oops, I thought it should be saved there ...

**Comment by SouzaRM** [comment]
That's it @PeterDaveHello! 
It is stored there [transgui.ini]:

(...)
[TorrentsList]
Id0 = 0
Width0 = 218
Index0 = 0
Visible0 = 1 <=== Visible or Not Visible
Id1 = 1
Width1 = 0
Index1 = 1
Visible1 = 0 <=== Visible or not visible
Id2 = 2
Width2 = 0
Index2 = 2
Visible2 = 0 <=== Visible or not visible
(...)

But my RWin 7 x64 does not assume this when I change from PC (idem Rwin 7 x64).

Thanks thanks @PeterDaveHello...

**Comment by SouzaRM** [comment]
I was able to correct:

Import does not inherit the columns.

But when copying the original [transgui.ini] from the other machine, the app opens 100% just like another machine, including the columns.

Grateful for your attention @PeterDaveHello

**Comment by PeterDaveHello** [comment]
@SouzaRM cool. I didnt use import feature but directly copy the ini file so didnt notice that, thanks for sharing.
