### ISSUE TITLE
Auto adding .torrent (watch folder) on OSX doesn't work

### ISSUE THREAD

**Issue by theerror** [transmission-remote-gui/transgui#1145]
Related do #1070 

I'm not sure if it's configuration or bug issue. MacOS is still new for me from point of this "advanced configuration" stuff with _defaults_ tool. I do have version TRG 5.15.4 (16fe466).

My steps to set up:

1. Set conf. values (hope, this is correct way to do that)

```
UknownPC:~ panelacek$ defaults write com.transgui WatchLocalFolder ~/Downloads
UknownPC:~ panelacek$ defaults write com.transgui WatchInterval 2
UknownPC:~ panelacek$ defaults read com.transgui
{
    "NSNavLastRootDirectory:ChooseFolder:0" = "/Volumes/downloads";
    "NSNavLastRootDirectory:GetFile:0" = "~/Downloads";
    "NSNavPanelExpandedSizeForOpenMode:ChooseFolder:0" = "{712, 448}";
    "NSNavPanelExpandedSizeForOpenMode:GetFile:0" = "{712, 448}";
    WatchInterval = 1;
    WatchLocalFolder = "/Users/panelacek/Downloads";
}
```
2. place .torrent file to  ~/Downloads
```
UknownPC:~ panelacek$ ls ~/Downloads/*.torrent
/Users/panelacek/Downloads/whatever.torrent
```
3. Start Transmission Remote GUI

The torrent file is still on place and it's not added to download queue.

**Comment by antekgla** [comment]
I dont have any macOSX machine or any mac experience but I think what **transgui.ini** would be in:

`/Users/panelacek/.config/Transmission Remote GUI/transgui.ini `

edit that file with the values you want. 
**Close any instance of TransGUI running before the edit.**

**Comment by theerror** [comment]
@antekgla You are totally right. Which section it belongs to? In `Interface` it won't work. Is there any option of logs, co I can see, it's checking?

```
[Interface]
[MainForm]
[Shortcuts]
[Hosts]
[Connection.xxxxxx]
[Translation]
[AddTorrent.xxxxxx]
[TorrentsList]
[FilesList]
[PeerList]
[TrackersList]
[PeersList]
[NetWork]
[StatusBarPanels]
```

**Comment by antekgla** [comment]
The value would be added in the Interface section...
See #1070 
I dont know why dont work in macOSX.
That is why I want testers in OSX and Linux.
Try to add the **WatchLocalFolder**  like 
`/Users/panelacek/Downloads`
and not like
`~/Downloads`

I read several post of problems in OSX and a lot of that problems are permission related. Check if TransGUI have the right permissions to write in **/Users/panelacek/Downloads** If that folder are not writable for TransGUI this feature is disabled.

...maybe some user with OSX experience would help in this...

**Comment by theerror** [comment]
OK, it's strange. Today I startup log console and TransGUI to see some problems and voila - torrent added. 

The `~` was the first what comes to my mind to get off, when it doesn't work. Actually - the problem could be related to some strange behaviour of Finder, because in same time it refused to connect to any SMB share.

Anyway, good, that it's working now fine. Thank you for that feature! If you implement it somewhere in UI it would awesome! :)

End, when you would need to test something on OSX ping me and I will do my best. It's even for Unix (Ubuntu) however I'm not using it so often.
