### ISSUE TITLE
Feature Request : Per-tracker ratio limit

### ISSUE THREAD

**Issue by menaren** [transmission-remote-gui/transgui#1147]
Hi, 

Would it be possible to set a ratio limit on a specific tracker ? 

It is not a feature from Transmission server, but it could be achieved by adding the torrent, then checking the configuration and change the ratio limit on the just-added torrent.

This option would override the global ratio limit.

**Comment by leonsoft-kras** [comment]
Hi!
I think your proposal is not clear.

**Comment by menaren** [comment]
Hi, sorry i'll try my best to be more precise. 

Today, there is the global ratio limit which is applied by the server on each added torrent. 
We can change this ratio limit on a specific torrent by right clicking on it and change that value in the settings. 

What I would like to do is make the tracker name right clickable (inside the left panel) and bring a setting to change the ratio limit for every torrent using this tracker.

Sometimes there are private trackers who are asking for a X ratio seed/leech and there are public trackers. 
It's kind of harassing to change manually the ratio for every torrent according to it's tracker.
This is why i'd like to know if this request is possible.

Since this is not a feature from transmission-server (ratio-per-tracker), it won't be possible to send a request to it's API. 
One way of doing it would be to add a new step after the addition of a new torrent to change it's ratio if a setting is applied on the tracker.

Hope this is better :)
Best Regards

**Comment by leonsoft-kras** [comment]
describe your manual actions, how you solve the problem now (if possible)

1. opened the window XXX
2. Counted the number of PI
3. Introduced in such a window PI / 10

**Comment by menaren** [comment]
1. Open the transmission-remote main UI (connected to a transmission-server with active torrents)
2. Scroll down on the left panel to get the list of trackers, 
3. Left click on one tracker to filter the torrents.
4. Ctrl+A to select all the torrents (which are using the previously selected tracker)
5. Alt+Enter to open the settings window
6. Untick the ratio limit (which has been applied by the global ratio limit)
7. Validate
8. Restart all the stopped torrents (eventually)

**Comment by menaren** [comment]
1. Open the transmission-remote main UI (connected to a transmission-server with active torrents)
2. Scroll down on the left panel to get the list of trackers, 
3. Left click on one tracker to filter the torrents.
4. Ctrl+A to select all the torrents (which are using the previously selected tracker)
5. Alt+Enter to open the settings window
6. Untick the ratio limit (which has been applied by the global ratio limit)
7. Validate
8. Restart all the stopped torrents (eventually)
