### ISSUE TITLE
Does not save the set columns settings

### ISSUE THREAD

**Issue by cry0xen** [transmission-remote-gui/transgui#1149]
transmission 2.94/remote gui v5.15.4
os win7

Transmission remote gui Does not save the set columns settings. Each time the programme restarts, it goes back to default settings. I have to reorganize my columns, add or remove them and sort them to my customization. doing this every time when client restarts is very irritating.

In SPECIFIC, these are needed to implemented to have better user experience- 
  1. transgui need to remember columns added by the user.
  2. It needs to remember the sorting order of torrent list.
  3. Ctrl+Shift shortcut not working [ctrl and shift work separately but not together. e.g. suppose you are going to chose 3 sets(1 bundle = few torrent) of torrents within the list but they are not one after one. with CTRL it'll be time consuming and with shift you will need to do it 3 times after action. but ctrl+shift you can do it in a single selection. very helpful for users with large number of torrents. ]

**Comment by antekgla** [comment]
TransGUI remember every setting of Torrentlist, Filelist, Peerlist, Trackerlist. Every one of them have his section in **transgui.ini** where is saved all the columns and the sort order.
Check your transgui.ini

**Comment by cry0xen** [comment]
Yep it works after reinstalling. here this may be result of one of 2 option(you'll know better)

1. while updating, I overwrote previous installation (installing without uninstalling old version)
2. permission issue may be. it was in c/program files

Any thank you for the hint. Issue closed.

P.S. Please consider adding Ctrl+Shift selection feature.
