### ISSUE TITLE
Add search facility for torrent list

### ISSUE THREAD

**Issue by d4nirod** [transmission-remote-gui/transgui#1154]
When you have a large number of torrents in the view it would be very useful to locate a particular torrent by entering a string so the programs searches the list of names of the currently loaded torrents trying to find a partial match.
Some transmission remote clients have this, e.g. Torrnado for Android https://play.google.com/store/apps/details?id=com.gabordemko.torrnado and it works pretty well (see magnifier at bottom right corner).

**Comment by antekgla** [comment]
That it is already implemented...

![search](https://user-images.githubusercontent.com/24402722/43677058-4b2e38e0-97d2-11e8-80c3-5bab1fa9d4de.jpg)

Any string there filter your torrent list.

**Besides when the torrent list have focus if you type any string the program try to find a partial match for that string.** Sadly that string is not displayed anywhere and there is not a Search Again (F3 in other programs) to find the second match.... but the workaround is type to find the first hit, then press down and type again to find the second match and so on.

**Comment by d4nirod** [comment]
🤦‍♂️ how did I missed that?
> when the torrent list have focus if you type any string the program try to find a partial match for that string.

That's more or less what I was trying to do but the existing facility is good for now.
Thanks

**Comment by skobkin** [comment]
It would probably better to move this field in the upper right corner so it will look more intuitive.

**Comment by garoto** [comment]
> It would probably better to move this field in the upper right corner so it will look more intuitive.

Upper right corner would feel more natural indeed. Its current placement is kinda awkward.
