### ISSUE TITLE
Feature request: Change to a second local pathway on finish (hardlinking via organizer tool)

### ISSUE THREAD

**Issue by iwconfig** [transmission-remote-gui/transgui#1169]
In situations where you utilize _hardlinking_ with an organizer tool for your downloaded content, the path to the content changes.

For example, I use Filebot to hardlink the downloaded content into formatted pathways at another location on my NAS. It would be awesome if the gui changed to a second local path way when the download is completed.

Since a hard link doesn't work across different filesystems, the directory for incomplete files won't work. This would be a request of multiple directories for incomplete files, in that case.

**Comment by leonsoft-kras** [comment]
![default](https://user-images.githubusercontent.com/11468577/46604330-15353280-cb20-11e8-8756-ae66b565f5cd.png)

doesn't it fit?

**Comment by iwconfig** [comment]
Oh, I forgot about that. The thing is I use two different disks and since a hard link doesn't work across different filesystems, so that function is of no use to me unfortunately.

**Comment by leonsoft-kras** [comment]
Each torrent can be saved to any disk. During the download, it will be in the temporary folder, and then the transmission should move your file to the desired folder.

TRGUI is not related to these manipulations.

**Comment by iwconfig** [comment]
I know, but the transfer and load takes up some time. If there is multiple files in a torrent, does a file get transferred independently as soon as it's finished apart from the rest?

I can understand why this request would be low priority, no worries!

**Comment by leonsoft-kras** [comment]
Most likely the request is not at the address.
The TRGUI displays what the transmission is doing.

**Comment by iwconfig** [comment]
Yes, you're right, but my request has to do with TRGUI:

![skarmklipp](https://user-images.githubusercontent.com/10843441/46608804-40ab2380-cb06-11e8-87e3-de01a98b3352.PNG)

What I'm after is something like this:

![skarmklipp](https://user-images.githubusercontent.com/10843441/46609170-579e4580-cb07-11e8-85da-0c7f00a5938c.PNG)

**Comment by iwconfig** [comment]
It's hard to believe that's the only option. I guess labels, tags and templates are in the same area as this. Anyways, I tried and at least i gave you my thoughts. I like this software, thank you.

Cheers!

**Comment by leonsoft-kras** [comment]
the appeal will still be on the path \\ arkivet \ ... \ downloads.
you will not see in the program \ TV shows.

and yes, this program (source code) is hard to maintain (I'm not the author)
