### ISSUE TITLE
Path error when adding torrent from WAN

### ISSUE THREAD

**Issue by chchia** [transmission-remote-gui/transgui#1170]
1. Operating system
Windows 10 x64 1809

2. Transmission Deamon
Transmission-daemon running in windows 10 2.94

3. Transmission Remote GUI
Transgui 5.15.4

Error:
When adding torrent from Transmission-Remote-Gui remotely (not on the LAN, but remotely from PC outside the LAN), it will give error "download directory path is not absolute".

due to it is remotely outside the LAN, i had tried all combination of path mapping but it is not working.

remotely using chrome extension Remote Transmission++ to add torrent outside the LAN is working correctly. so i guess my knowledge of setting is not good enough, or maybe the issues could be within Transmission Remote GUI itself.  

ps: this error only happend when adding new torrent. I can "Set data location" remotely from WAN without any problem.

**Comment by chchia** [comment]
update: fixed by complete uninstall transgui and reinstall....

**Comment by ingria** [comment]
Still having this problem on 5.18.0
