### ISSUE TITLE
New version 5.16

### ISSUE THREAD

**Issue by leonsoft-kras** [transmission-remote-gui/transgui#1182]
@PeterDaveHello Please see what the problems are in travis

**Comment by PeterDaveHello** [comment]
Break by: https://github.com/transmission-remote-gui/transgui/commit/324bff947376508bcdc03db72291cec0517aedc5, I don't think it's just extra space issue, and I don't really know what happened but it must be related with the codes there, is there no issues with your local environment? I prefer to revert that change, and commit the code part by part, sending pull request, so we know which part goes wrong.

**Comment by leonsoft-kras** [comment]
I dont understand too. : ((
There was a minimum of changes. Spaces were in the files before.

I will try to change something.

**Comment by PeterDaveHello** [comment]
So with all due respect, I suggest separating the commit properly with minimum changes, that'll help debug and code trace.

**Comment by leonsoft-kras** [comment]
I edited the makefile. The program file will be large, because debug information will now be generated.

If the program crashes, a crashreport.txt file will be created.
This file must be sent to us for analysis. It will contain the line number of the failure.

Hopefully we will be able to extend this to all operating systems.
So we can quickly be the cause of failure of users.

**Comment by leonsoft-kras** [comment]
@PeterDaveHello I have corrected, understood the problems. 
Now Travis runs without errors :))

Can you fix hystory (English) and release 5.16?

**Comment by PeterDaveHello** [comment]
@leonsoft-kras thanks, I'll try to make it the next week.

**Comment by PeterDaveHello** [comment]
https://github.com/transmission-remote-gui/transgui/releases/tag/v5.16.0
