### ISSUE TITLE
Help needed: "Host not found"

### ISSUE THREAD

**Issue by anohren** [transmission-remote-gui/transgui#1186]
1. Operating system
macOS 10.14.1

2. Transmission Deamon
transmission-daemon 2.93 (3c5870d4f5)

3. Transmission Remote GUI
16fe466

I cannot seem to find instructions on how to get started. Sorry if I missed some obvious help page. All I get when I try to use the app is "Host not found" over and over.

In transgui I've filled in:
Remote host: `rpi.local`
Port: `9091`
RPC path: `/transmission/` or `/transmission/rpc/`

The default `/transmission/rpc/` didn't work — not sure where I get this path from, I just guessed that it's the same as `rpc-url` in `settings.json`. Since the documentation for `settings.json` only seems to have super helpful descriptions like "rpc-url: String (default = /transmission/. Added in v2.2)" I doubt I can figure these settings out.

In transmission's `settings.json` I have e.g.:
```
    "rpc-authentication-required": false,
    "rpc-enabled": true,
    "rpc-host-whitelist-enabled": false,
    "rpc-port": 9091,
    "rpc-url": "/transmission/",
    "rpc-username": "",
    "rpc-whitelist": "*.*.*.*",
    "rpc-whitelist-enabled": true,
```

I can access the web ui and I can `transmission-remote rpi.local -l` from the remote machine. 

How is this application meant to work?

**Comment by leonsoft-kras** [comment]
execute:
    ping rpi.local
What does the utility display on the screen?

execute:
    telnet rpi.local 9091
What does the utility display on the screen?

execute:
    nc -v telnet rpi.local 9091
What does the utility display on the screen?

**Comment by anohren** [comment]
```
$ ping rpi.local
PING rpi.local (192.168.0.3): 56 data bytes
64 bytes from 192.168.0.3: icmp_seq=0 ttl=64 time=13.393 ms
```

```
$ telnet rpi.local 9091
Trying 192.168.0.3...
Connected to rpi.local.
Escape character is '^]'.
```
```
$ nc -v telnet rpi.local 9091
nc: port range not valid
```


Turns out the application is just buggy; I changed my mDNS address to the corresponding ip-address and now it works. I doubt this will be very useful outside the local network though, if it cannot resolve addresses from hostnames.

Similarly I can't browse for a download destination in the download options' prompt after having mapped my folders with `...=smb://rpi.local/...`

**Comment by leonsoft-kras** [comment]
These are some problems with mDNS in MacOS. The program applied through regular functions to determine the IP address. The operating system returned an error to it.

The program should not care if there is an mDNS on the computer or not. You can ask the Lazarus forum with a question (support for converting a computer name to an address in the Mac OS).

**Comment by anohren** [comment]
Oh ok, thanks. If I understood you correctly it should at least work with regular DNS?

Don't know what Lazarus is, sorry! Just tried out the app for the first time.

**Comment by leonsoft-kras** [comment]
Winvdos and Linux users did not report the problem.

The program is written in pascal.
https://www.lazarus-ide.org/

**Comment by sekrett** [comment]
I typed IP address and it connected. :)

**Comment by PeterDaveHello** [comment]
Let's move to #1127 (https://github.com/transmission-remote-gui/transgui/issues/1127), thanks for the feedback and discussion here.
