### ISSUE TITLE
[Bug] Missing columns in v5.16.0

### ISSUE THREAD

**Issue by PeterDaveHello** [transmission-remote-gui/transgui#1189]
1. Operating system: Linux Mint 19 Tara
2. Transmission Deamon: v2.92
3. Transmission Remote GUI: v5.16.0

v5.15.4: ![Screenshot](http://i.imgur.com/N5PS0ma.png)
`Total`, `Selected` & `Done` columns are here at the right bottom corner  :arrow_upper_right: 

v5.16.0: ![Screenshot](https://i.imgur.com/UwdcXsL.png)
`Total`, `Selected` & `Done` columns are missing at the right bottom corner  :arrow_upper_right:

**Comment by CnuPuH** [comment]
Not because of this by chance?
https://github.com/transmission-remote-gui/transgui/issues/1163
 Just disabled the status bar ...

**Comment by antekgla** [comment]
Just check in the menu:
**View --> StatusBar Sizes**

**Comment by PeterDaveHello** [comment]
@antekgla didn't know it's not enabled by default, maybe we could do so, so the default behavior didn't changed? Thanks!

**Comment by PeterDaveHello** [comment]
@CnuPuH nope :)

**Comment by PeterDaveHello** [comment]
@antekgla thanks, didn't notice it's now default disabled. Would be more careful next time.

**Comment by afrojewelz** [comment]
still , some of our client even enable `Total`, `Selected` & `Done` is now showing selected size. plz help

**Comment by afrojewelz** [comment]
check in the menu:
**View --> StatusBar Sizes** wouldn't do any help.

**Comment by leonsoft-kras** [comment]
The function is not fundamentally changed in the new version. 
If the "status bar-sizes" is turned on in the menu, then there should be 3 fields in the status bar.

In the procedure "procedure TMainform.StatusBarSizes", the calculation algorithm was changed only to increase the speed.
I dont see the difference between the versions. I can still turn on/off the display of this fields.

***
there is a difference only in main.lfm
In the old version, the default option was selected.
in the new version - the default option is not selected.

![image](https://user-images.githubusercontent.com/11468577/53331565-cbf54c00-3923-11e9-8ca0-17c3f44c60f8.png)

**Comment by afrojewelz** [comment]
> izes", the calculation algorithm was changed only to increase the speed.

i can understand some people got performance leaning on this function ,isn't good practise 
let user decide get rid of the select item size calculate to increase performance while other people can still have this function that they thought this is a remote client,we just satisfied with its usual performance?

**Comment by leonsoft-kras** [comment]
Speech that function works. Nobody turned off the windows and functionality in the new version.

You must enable the option in the menu, it is possible to restart the program. New fields should be displayed in the status bar.

**Comment by antekgla** [comment]
@afrojewelz what is your issue with this function?
When you check in the menu **View --> StatusBar Sizes**  the new values dont show at all in the status bar or in your opinion that values are not correct?
Please clarify your problem, because @PeterDaveHello @leonsoft-kras and I have checked this and that values appears when you have selected the proper option in the menu.

**Comment by leonsoft-kras** [comment]
At the beginning of the topic, see 2 pictures. 
Only there is no clarity what is selected in the menu.

**Comment by antekgla** [comment]
@leonsoft-kras that messages are from @PeterDaveHello 
@afrojewelz  seems like having another problem.

**Comment by PeterDaveHello** [comment]
Yeah, I just forgot about the changed default value, manually enabled it and it works again!

**Comment by PeterDaveHello** [comment]
@afrojewelz seems to have an issue that the same behavior doesn't work there.

**Comment by afrojewelz** [comment]
@antekgla i think the 5.16.0 seems disrupt the  selected size viewing in status bar. i thought this was the colume the new version was missing.

**Comment by antekgla** [comment]
@afrojewelz  I don't see this kind of behavior you describe in 5.16.0 (Win32 portable download)

I explain the values:

**Total**: the sum of the complete size of all torrents (sum of **Size** column)
**Selected**: the sum of the size ONLY of the files you choose to download (sum of **Size to Download** column)
**Done**: the sum of the bytes downloaded of the selected torrents (sum of **Downloaded** column).
**Remaining**: The difference between **Selected** - **Done**

If only ONE TORRENT is selected in torrent list this amounts is the sum of ALL TORRENTS (it is not possible select none torrent)
If more of one torrent is selected this amounts are the sum of only that torrents.

If your 5.16.0 dont show this values please post a screenshot of 5.16.0 and another from a previous version with the same torrents selected.

**Comment by afrojewelz** [comment]
@antekgla as you wish .
![5 11trguihasfunctional selected size](https://user-images.githubusercontent.com/1831795/54024480-d987bd00-41d2-11e9-8aa7-6aaf7a54e508.png)
![5 16trguihasfunctional selected no size with size colume option](https://user-images.githubusercontent.com/1831795/54024481-da205380-41d2-11e9-952a-2ea877c928a2.png)
![5 16trguihasfunctional selected no size](https://user-images.githubusercontent.com/1831795/54024482-da205380-41d2-11e9-879b-ef62cf2a1bd8.png)

**Comment by antekgla** [comment]
@afrojewelz 
Check this menu item and **WAIT A FEW SECONDS**... the values would appear in the status bar

![Status Bar Sizes](https://user-images.githubusercontent.com/24402722/54081054-97e33900-42dc-11e9-988e-415bcb0e4704.jpg)

**Comment by PeterDaveHello** [comment]
@afrojewelz do you still have the issue?

**Comment by afrojewelz** [comment]
> a
sorry reply late,the issue was solved during  5.17
 great works many thanx
