### ISSUE TITLE
Transmission sometimes download to the root directory

### ISSUE THREAD

**Issue by ViBE-HU** [transmission-remote-gui/transgui#1192]
1. Operating system: Windows 10
2. Transmission Daemon: 2.84 (14307)
3. Transmission Remote GUI: 5.16 but I noticed this sinece 5.x afair

So the daemon running on a WRT environment but I guess the issue is with the client. When I try to add a torrent it looks like the client already allocate the space for the content or something like that while the panel is still open and waiting for the add. No matter what direction I choose it will add it to the root. 

For an example I download a series into a subdirectory, absolutely sure that I set this from the list when I add:
/media/Series

Then the client will download here:
/media

No matter if I move it to the right directory after it finished because it will move back after a while.

**Comment by leonsoft-kras** [comment]
Torrents downloads and writes the transmission daemon.
Check work with the transmission through the website or in the transmission.

**Comment by ViBE-HU** [comment]
@leonsoft-kras Not sure what would you like to tell me but I don't experiencing this issue if I add via the web interface.
