### ISSUE TITLE
GeoIP Data download 404!

### ISSUE THREAD

**Issue by flyqieqq** [transmission-remote-gui/transgui#1195]
![snipaste_2019-01-06_11-59-00](https://user-images.githubusercontent.com/21137644/50731938-8d0c0b00-11aa-11e9-973f-33bf15b003ea.png)

**Comment by PeterDaveHello** [comment]
That's same issue here: #1104

**Comment by cybersteel8** [comment]
Looks like GeoIP2 databases are available, but some implementation must be changed.
https://dev.maxmind.com/geoip/geoip2/downloadable/

**Comment by vodek3** [comment]
The latest version of GeoIP.dat can be downloaded and extracted from the RPM package here:
http://rpms.remirepo.net/rpmphp/zoom.php?rpm=GeoIP-GeoLite-data
https://dl.fedoraproject.org/pub/fedora/linux/development/29/Everything/source/tree/Packages/g/GeoIP-GeoLite-data-2018.06-2.fc29.src.rpm
http://dl.fedoraproject.org/pub/fedora/linux/updates/testing/28/Everything/SRPMS/Packages/g/GeoIP-GeoLite-data-2018.04-1.fc28.src.rpm

GeoIP-GeoLite-data-2018.04-1.fc28.src.rpm
or
GeoIP-GeoLite-data-2018.06-2.fc29.src.rpm

* Tue Jun 19 2018 Paul Howarth <paul@city-fan.org> - 2018.06-1
- IPv6 databases are still seeing updates in June 2018
- IPv4 databases are unchanged from previous release

* Wed Apr 4 2018 Paul Howarth <paul@city-fan.org> - 2018.04-1
- Final update of GeoLite Legacy databases from Maxmind

**Comment by vodek3** [comment]
Only GeoIP.dat - April 2018
https://cloud.mail.ru/public/94yN/aytiNxfMR

**Comment by saspol** [comment]
Where to put this GeoIP.dat on OSX?

**Comment by PeterDaveHello** [comment]
@saspol Try /Users/username/.config/Transmission Remote GUI/ ?

**Comment by xuexiaokang** [comment]
C:\Users\XXXXXXXXXXXX\AppData\Local\Transmission Remote GUI

**Comment by arbv** [comment]
The other possibility is to get the required database files from the Arch Linux binary package:

https://www.archlinux.org/packages/extra/any/geoip-database/download/

These are located here:

`usr\share\GeoIP\`

You might require some archiver which supports unpacking `.tar.xz` archives (e.g. 7-Zip).

Put them into the `%USERPROFILE%\AppData\Local\Transmission Remote GUI` directory or the Transmission Remote GUI installation directory.

Here I assume that you use Windows.

**Comment by saspol** [comment]
> Try /Users/username/.config/Transmission Remote GUI/ 
Thanx, this works.

**Comment by cry0xen** [comment]
> Only GeoIP.dat - April 2018
> https://cloud.mail.ru/public/94yN/aytiNxfMR

can you please reupload them somewhere else?

**Comment by saspol** [comment]
> can you please reupload them somewhere else?

https://cloud.omahum.net/s/44o3taBmApw7tWf

**Comment by cavalli1021w** [comment]
Tried to download various links.  Extracted and put into exe directory.  Manual zip extract install to custom path:  C:\MyBin\x86\TransGUI\transgui.exe and put GeoIP.dat.gz and GeoIP.dat in same directory.  Can't turn on "show country flag" as it downloads and shows the 404 error.  Tried to set both flags to '1' in transgui.ini (also in TransGUI manual directory) to no avail.  No instructions on how/where to put this file.  Any information appreciated.  Thanks!

**Comment by vodek3** [comment]
> ...put GeoIP.dat.gz and GeoIP.dat in same directory...

You need only GeoIP.dat.
Put it in case portable installation in same folder with TransGUI.exe
otherwise in folder %localappdata%\Transmission Remote GUI (C:\Users\%UserName%\AppData\Local\Transmission Remote GUI).

**Comment by vodek3** [comment]
> 
> 
> > Only GeoIP.dat - April 2018
> > https://cloud.mail.ru/public/94yN/aytiNxfMR
> 
> can you please reupload them somewhere else?

https://mir.cr/1JFD47CA

**Comment by cavalli1021w** [comment]
Got everything up and running again.  Your GeoIP.dat file and flags.zip in the .ini directory, and everything working great again.  Had a couple of countries that didn't have country info, because the GeoIP file is out of date with 2018 information.  Found someone who is converting the current information and has more up to date files.  Here's the link:
https://www.miyuru.lk/geoiplegacy

I am using the DB-IP IPv4 file and renaming it to GeoIP.dat and it seems to be more complete than the one you posted.  Reposting this information here in case it can be used to automate future versions of TR GUI.

Thanks for the help!

**Comment by PeterDaveHello** [comment]
@cavalli1021w thanks for the info, we will see if we can directly use it.

**Comment by miyurusankalpa** [comment]
@cavalli1021w thanks for the mention. 👍 

@PeterDaveHello if you need any help or more info, please reach out.

**Comment by lointain74** [comment]
@vodek3 Thankx. Working great!!!

**Comment by xeverse** [comment]
ThanXx, that did the trick. Moreover,
the GeoIp db contains City info as well..
infoPane/Peers -- City column would be 
just perfect; along-side with cntry & flags..

**Comment by Gertcha** [comment]
What does this data do and how will not updating affect the performance and function of TRG? I did update this before I did my last clean install but couldn't appreciate any difference from doing so just as having not updated it 😕

**Comment by PeterDaveHello** [comment]
@miyurusankalpa do you mind us directly point the download link to https://dl.miyuru.lk/geoip/maxmind/country/maxmind4.dat.gz 😄? It'll be very helpful before we have enough time to rewrite the codes, thanks!

**Comment by miyurusankalpa** [comment]
@PeterDaveHello Not at all. that subdomain is aggressively cached with cloudflare.

**Comment by PeterDaveHello** [comment]
Thank you @miyurusankalpa

**Comment by PeterDaveHello** [comment]
For GeoIP/GeoLite v2 upgrade related issue, feel free to discuss in #1104.

**Comment by cavalli1021w** [comment]
Saw the new updated DB so tested the "Update GeoIP database" option in "Tools".  Error message "SSL/TLS support is not compiled!".  Another "Downloading" box shows "maxmind4.dat.gz", if that helps.  The manual download of the DB-IP IPv4 file and renaming it to GeoIP.dat still seems to work.

Hope that helps!  :D

**Comment by PeterDaveHello** [comment]
@cavalli1021w please open an issue with environment details, thanks.
