### ISSUE TITLE
Clean/clear location history

### ISSUE THREAD

**Issue by wjk82** [transmission-remote-gui/transgui#1196]
How to clean (remove some paths) or at least clear them all?

![iv6htf0](https://user-images.githubusercontent.com/20017577/50777230-506c0c80-129b-11e9-9908-d75187d27f19.png)

Didn't see in options anywehere, nor in config file. Where Transmission Remote GUI store this info?

This is history displayed in "Change location" window (F6) or "Add new torrent" window.

**Comment by leonsoft-kras** [comment]
![default](https://user-images.githubusercontent.com/11468577/50777908-5b409480-12cf-11e9-9aae-d076972d52d1.png)
There is such a way.

**Comment by wjk82** [comment]
Thanx @leonsoft-kras, missed that. All ok now.

**Comment by urda** [comment]
This button doesn't seem to clear any history on my version:

<img width="533" alt="image" src="https://user-images.githubusercontent.com/1648492/115761652-6e1feb80-a357-11eb-906b-9c7125130259.png">

I click it, and nothing seems to happen. There is no GUI change, and the drop down still has a long list of previous paths.

**Comment by DuncanHills** [comment]
Would it be possible to add this button to the "set data location" dialogue box?
