### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by thany** [transmission-remote-gui/transgui#1203]
How do I set the application to dark mode?
In the readme file, the first image we see, is the application in beautiful dark mode. But I can't find a way to set it like that. It's always glaring white.

I've already enabled Windows 10 dark mode, and some applications respond to it. Some very well actually. Looking at the screenshot, the application _can_ apparently be dark, and/or respond to a system theme. Which in my case it doesn't, or I don't know how to make it.

Can we please have this for real?

Windows 10 build 1809
Transmission 2.94
Remote GUI 5.16.0

**Comment by PeterDaveHello** [comment]
it's a system theme on Linux distrobution, if you have kind of them tools on Windows, then you can do something like that, transgui doesn't support native dark theme yet.

**Comment by PeterDaveHello** [comment]
Dup of #998
