### ISSUE TITLE
macOS 10.15 DP1

### ISSUE THREAD

**Issue by srscott** [transmission-remote-gui/transgui#1222]
1. macOS Catalina 10.15
2. Transmission Deamon
3. Transmission Remote GUI

Application will not launch in new macOS 10.15
"Transmission Remote GUI" needs to be updated.
The developer of this app needs to update it to work with this version of macOS. Contact the developer for more information.
![Screen Shot 2019-06-06 at 9 24 42 am](https://user-images.githubusercontent.com/17326832/58997704-f3ba5100-883c-11e9-83b5-287fbfce9504.png)

**Comment by leonsoft-kras** [comment]
repeat

**Comment by leonsoft-kras** [comment]
https://github.com/transmission-remote-gui/transgui/issues/1150

**Comment by techo91** [comment]
That would be very nice to have.
