### ISSUE TITLE
v5.17.0 and MacOS Catalina 10.15

### ISSUE THREAD

**Issue by LStester** [transmission-remote-gui/transgui#1227]
Hi pls add MacOS Catalina 10.15
but in catalina transgui not work (

thanks!

**Comment by PeterDaveHello** [comment]
@LStester see #1150 #1224

**Comment by LStester** [comment]
> @LStester see #1150 #1224
sorry i’am not programmer
could you compile and upload to dropbox or google disk pls?

**Comment by PeterDaveHello** [comment]
@LStester nope, as you can see, it's not finished.

**Comment by LStester** [comment]
> @LStester nope, as you can see, it's not finished.

thanks, i’am looking forward to support catalina in your program!

**Comment by PeterDaveHello** [comment]
Close as duplicate of #1150
