### ISSUE TITLE
Connection refused -- doesn't appear to be trying to connect (both Ubuntu and MacOS)

### ISSUE THREAD

**Issue by ndrwstn** [transmission-remote-gui/transgui#1230]
Operating System: Ubuntu 19.04 and MacOS 10.14.5
Daemon: Transmission 2.94 (via linuxserver/transmission docker container)
Remote GUI: 5.17.0

Connection refused without further information. I can't find any logs showing why. I ran a network capture (on MacOS), but it only results in a (successful) DNS resolution, it doesn't appear to try to connect to the remote daemon at all. Transmission-daemon is running on a remote server, but is accessible via the web (both at /transmission/web and /transmission/rpc -- verified with wget).

Entirely possible this is my error, however without any log files (that I can find) I'm at a loss. I also couldn't find any command-line flag that might create additional log files.

**Comment by PeterDaveHello** [comment]
@ndrwstn can you use curl or wget to try to connect to the address and port you configured for transgui ans see the response?

**Comment by ndrwstn** [comment]
The command and response. If I don't put in the correct/recent token, I get the 409/Conflict from CSRF, but once I put in the correct token, I'm able to get a 405/Method not allowed error. While I don't understand Transmission's RPC spec, it seems that the connection is open/accepted. If I knew how to pass a valid method using wget, I believe I could get a response. This seemed to indicate a possible problem with the GUI client end.

> wget --user=\<username\> --ask-password --header="X-Transmission-Session-Id: \<token\>" http://\<fqdn\>/transmission/rpc

results:

> --2019-07-02 00:20:23--  http://\<fqdn\>/transmission/rpc
> Resolving \<fqdn\> (\<fqdn\>)... 192.168.1.15
> Connecting to \<fqdn\> (\<fqdn\>)|192.168.1.15|:80... connected.
> HTTP request sent, awaiting response... 401 Unauthorized
> Authentication selected: Basic realm="Transmission"
> Reusing existing connection to \<fqdn\>:80.
> HTTP request sent, awaiting response... 405 Method Not Allowed
> 2019-07-02 00:20:23 ERROR 405: Method Not Allowed.

Username, password, and fqdn are all valid and work via the web interface, which also jives with the wget output. Port 80 is showing up there because I have a nginx proxy pointing to <ip>:9091. I would think that since its connecting, authorizing, then giving a 405 error, the reverse proxy isn't the problem. That could be wrong.

The only possible gotcha I have shouldn't be an issue, but I'll mention it. My password is >20 characters long and contains symbols. I wouldn't think this is a problem, but on the off-chance the GUI has a password bug, I figured I'd mention it.

Let me know what other information I can provide and I'll likely get it back to you tomorrow. Thanks.

**Comment by ndrwstn** [comment]
I switched from nginx-proxy to Traefik and this issue disappeared. I'm going to assume it was my problem and close this out. Thank you.

**Comment by PeterDaveHello** [comment]
Thanks, guess it should be configuration issue, I've been using nginx as proxt to connect to transmission-daemon before and it always works fine.
