### ISSUE TITLE
Did the "Remaining" number in the status bar disappear?

### ISSUE THREAD

**Issue by LordMike** [transmission-remote-gui/transgui#1233]
Hi,

I just updated to `5.17.0`, and it seems I've lost a few numbers in the status bar. The dividers are still there - so perhaps it's an error?

![image](https://user-images.githubusercontent.com/1027111/60772586-ecff5200-a0f8-11e9-8b2a-8879748f9443.png)

I was looking for the "Remaining" number to see what a selection of torrents was missing.

Mike.

**Comment by leonsoft-kras** [comment]
repeat.

menu -> view -> status bar-sizes
