### ISSUE TITLE
Windows x64 - can't load openssl dlls

### ISSUE THREAD

**Issue by ornic** [transmission-remote-gui/transgui#1238]
When installed via x64 installer and trying to connect to daemon via SSL, I got error mesasges "unable to load dls" and then "not compiled with ssl support".

1. Operating system: **Windows 10 Pro 1903 18362.239**
2. Transmission Deamon **2.94**
3. Transmission Remote GUI **5.17.0**

WIndows installer for 32bit worked normal.

**Comment by a10kiloham** [comment]
i'm getting same error upgrading from the Sourceforge binary to the 64bit version

**Comment by boozyy** [comment]
![Ca67876pture](https://user-images.githubusercontent.com/32224944/61992898-1c0c4200-b06d-11e9-864f-c87906c086b8.PNG)

Getting this error trying to install 64bit experimental build on Win7 64bit and Transmission daemon 2.93.

**Comment by hapylestat** [comment]
same error when trying to update GeoIP database

**Comment by hapylestat** [comment]
found workaround: download  [OpenSSL x64 Binaries](https://indy.fulgan.com/SSL/openssl-1.0.2s-x64_86-win64.zip)  (openssl-1.0.2s-x64_86-win64.zip)

Unpack libeay32.dll and ssleay32.dll to "C:\Program Files (x86)\Transmission Remote GUI" and restart client.

**Comment by boozyy** [comment]
> found workaround: download [OpenSSL x64 Binaries](https://indy.fulgan.com/SSL/openssl-1.0.2s-x64_86-win64.zip) (openssl-1.0.2s-x64_86-win64.zip)
> 
> Unpack libeay32.dll and ssleay32.dll to "C:\Program Files (x86)\Transmission Remote GUI" and restart client.
> 
> @PeterDaveHello problem with x64 installer. It shouldn't put the application to "Program Files (x86)", instead should be used "Program Files"

Can confirm, the workaround seems to work. Thanks!

**Comment by PeterDaveHello** [comment]
It's an experimental release, let's move to #1047 for further discussion, thanks.
