### ISSUE TITLE
64bit macOS version required

### ISSUE THREAD

**Issue by CelticWebSolutions** [transmission-remote-gui/transgui#1242]
For bug report, please provide version info of:

For macOS 10.15 (still in Beta) the current version will not run due to the Mac version bing 32bit.  a 64bit Mac version will be required moving forward.

**Comment by CelticWebSolutions** [comment]
I tried installing Lazarus to compile a 64bit version on Catalina but it appears that Lazarus it's self is not yet compatible.

**Comment by PeterDaveHello** [comment]
@CelticWebSolutions See #1224 please

**Comment by CelticWebSolutions** [comment]
Hi @PeterDaveHello, thanks for the link.  I did search before posting but missed start one.  I'm hoping Lazarus will be updated with a full 64bit release so I can compile on 10.15 myself.  

Thanks
