### ISSUE TITLE
Notifications don't work

### ISSUE THREAD

**Issue by rd1** [transmission-remote-gui/transgui#1246]
i haven't been getting notifications from TRG in quite a long time, like when i add torrents or they finish.

i just finished testing all versions of TRG on Windows 10 x64 from 5.17 down to 5.03 using every setup.exe files from github and i don't see TRG in Windows 10's list of apps authorized to display a notification in the Windows 10 notification center. 

None of the installers has added TRG to the list of apps that use the notification system, i wonder if that could be why. Although some apps that aren't on the list do still show messages, maybe it's in the code instead ?

**Comment by antekgla** [comment]
By personal experience, notifications in W10 are erratic.
It happens to me:

- TRGUI shows me notifications normally.
- TRGUI don't shows me notifications.
- TRGUI show a notication behind  (for example after end torrent 1 don't show notication, then when ends torrent 2 show notication of end of torrent 1, then when ends torrent 3 show notification of end of torrent 2 and so on)

**All that with THE SAME version of TRGUI**... the only change the W10 version what update frequentely. When a new version of W10 appears notification behavior change.

So my conclusion is: is W10 fault.

**Comment by rd1** [comment]
in your case you may have focus assistant enabled. 

i do not.

this is a fresh new install from last week, no tweaking was done to windows, everything is freshly installed.

**Comment by rd1** [comment]
some new windows update has fixed the notifications on my 2 computers and tablet.

**Comment by antekgla** [comment]
I told you... its a Windows problem.
