### ISSUE TITLE
Mac OS X Catalina 64 bit required

### ISSUE THREAD

**Issue by Hevega** [transmission-remote-gui/transgui#1257]

**Comment by Aspdian** [comment]
Yes！I need!

**Comment by liquidblasted** [comment]
Need it too, coz I'm so sexy and this great app is sexy, so I love sexy apps, dear sexy developers please make it sexy in x64 too

**Comment by leonsoft-kras** [comment]
> 
> 
> Need it too, coz I'm so sexy and this great app is sexy, so I love sexy apps, dear sexy developers please make it sexy in x64 too

Apple has arranged sex for everyone (except developers).
Anyone can join the project to complete this sex.

**Comment by wilson111** [comment]
Yes, need 64-bit version too

**Comment by PeterDaveHello** [comment]
see https://github.com/transmission-remote-gui/transgui/issues/1150
