### ISSUE TITLE
macOS Catalina / 32-bit installation fails, Make it 64-bit

### ISSUE THREAD

**Issue by Yangseok** [transmission-remote-gui/transgui#1259]
1. Operating system - macOS Catalina 10.15
2. Transmission Deamon - I do not know
3. Transmission Remote GUI - transgui-5.17.0.dmg
<img width="748" alt="스크린샷 2019-10-09 오후 1 47 02" src="https://user-images.githubusercontent.com/6768687/66452409-59447580-ea9b-11e9-94b9-c50449dfaf74.png">

**Comment by leonsoft-kras** [comment]
#1150
