### ISSUE TITLE
Update for macOS?

### ISSUE THREAD

**Issue by sheykh-sleky** [transmission-remote-gui/transgui#1260]
Just updated to 10.15 Catalina and this broke.  <insert crying face>

**Comment by trenerok** [comment]
confirm same issue

**Comment by TeoBrachet** [comment]
Catalina doesn't support 32bits applications anymore, any plan for an 64bits macOS app ?

**Comment by David4D** [comment]
I confirm the same issue

**Comment by chkuendig** [comment]
See the alpha builds linked at https://github.com/transmission-remote-gui/transgui/issues/1150

**Comment by glorykim99** [comment]
the same issue!!
