### ISSUE TITLE
Multi download selection malfunction

### ISSUE THREAD

**Issue by m7911114k** [transmission-remote-gui/transgui#1261]
1. Operating system : Mac Mojave
2. Transmission Deamon : 2.94-16
3. Transmission Remote GUI : 5.18.0 Build 3fb1d33

When I select download mission (not sequential) always use command + left click, 
but somehow it doesn't work at 5.18.0. Sequential select with shift + left click is worked.

**Comment by hvisage** [comment]
Sequential selection for me works with just Shift+left click, but yes, the multiple/out-of0sequence is not working ;(

**Comment by dlovingood** [comment]
Same issue for me under MacOS Catalina with v5.18.0.  Command+click and Control+click both fail to select multiple items.  Control+click does work on the Windows version, at least on Windows 10.
