### ISSUE TITLE
32-bit Apps No Longer compatible with macOS Catalina

### ISSUE THREAD

**Issue by SparkyBoy51** [transmission-remote-gui/transgui#1264]
Just wondered if the 64-bit app for macOS is being planned for?

I didn't realise but now I can no longer user this app on macOS Catalina.
<img width="711" alt="Screenshot 2019-10-21 at 13 47 01" src="https://user-images.githubusercontent.com/48954992/67206815-54bc7d00-f40a-11e9-9f5a-a8950938863c.png">
<img width="421" alt="Screenshot 2019-10-21 at 13 46 22" src="https://user-images.githubusercontent.com/48954992/67206816-54bc7d00-f40a-11e9-96fc-5b21de6796ad.png">

**Comment by mikediachenko** [comment]
Also interested - when it is going to happen?

**Comment by anselmpaul** [comment]
`[Release 5.18.0](https://github.com/transmission-remote-gui/transgui/releases/tag/v5.18.0)` is built with 64 bit for macOS

**Comment by SparkyBoy51** [comment]
Thanks for the feedback - v5.18.0 works fine now on macOS Catalina.
