### ISSUE TITLE
MacOS Catalina - TransGUI doesn’t run.

### ISSUE THREAD

**Issue by barbequesauce** [transmission-remote-gui/transgui#1265]
Shouldn’t be a surprise, as Lazarus also doesn’t run - but I don’t see an issue on it anywhere....

**Comment by PeterDaveHello** [comment]
@barbequesauce please provide more details, with no detail information, no one will be able to help you.

**Comment by barbequesauce** [comment]
When you launch it you get this popup.

<img width="418" alt="Screen Shot 2019-10-23 at 12 35 45 PM" src="https://user-images.githubusercontent.com/25070944/67415090-5add6580-f592-11e9-93c5-f65633b2dd4e.png">

Clicking the "Learn More..." button takes you [here](https://support.apple.com/en-us/HT208436).

**Comment by Willian-Zhang** [comment]
worked for me on `19A602`
```
brew cask info transmission-remote-gui
transmission-remote-gui: 5.18.0
https://github.com/transmission-remote-gui/transgui
/usr/local/Caskroom/transmission-remote-gui/5.18.0 (2 files, 46.9KB)
From: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/transmission-remote-gui.rb
==> Name
Transmission Remote GUI
==> Artifacts
Transmission Remote GUI.app (App)
```

**Comment by barbequesauce** [comment]
🤦‍♂  sorry that was 5.16.
