### ISSUE TITLE
Dark mode on macOS

### ISSUE THREAD

**Issue by hekm77** [transmission-remote-gui/transgui#1268]
Text in the app is not visible.
Transmission Remote GUI 5.18.0
macOS Catalina 10.15.1 > Preferences > General > Appearance (Dark) > Highlight color (Graphite)

<img width="1286" alt="111" src="https://user-images.githubusercontent.com/22895433/68525181-4e197b00-02cf-11ea-9f4a-f4cab4be7a30.png">

**Comment by bonovski** [comment]
I second that, focus color needs a little change.

**Comment by mat813** [comment]
To make it a more complete example:

<img width="373" alt="screenshot 2019-12-19 à 08 30 40" src="https://user-images.githubusercontent.com/75783/71153663-f65d2080-2239-11ea-88cc-c82aa9cc90c3.png">

This is in the morning, when colors go from dark to light. It is the same mess in the evening when they go from light to dark.

**Comment by sIRwa2** [comment]
Yep, MacOS Dark mode Font color adjustment really appreciated!

**Comment by ormanya** [comment]
Same problem here.

**Comment by 0x5e** [comment]
same issue

**Comment by myrandor** [comment]
On Mac OSX Mojave in Dark Mode using 5.18.0, everything looks good except "Text Area" field. They use black font over dark grey background.

**Comment by reedy** [comment]
Only problem I've seen is when things are disabled... The labels look odd

<img width="640" alt="Screenshot 2020-05-03 at 03 48 52" src="https://user-images.githubusercontent.com/67615/80897484-052c0780-8cf1-11ea-8b29-f767093d420a.png">

**Comment by neo-neo1** [comment]
9 months and counting. Any active devs with the skill set to fix this and compile a dev build they can share? I'd be very grateful as well as others, I'm betting.

**Comment by asherman07** [comment]
here to report the same issues, hopefully someone will pick up the project and fix it!!

**Comment by BlackRockCity** [comment]
Here's the workaround. It won't give you dark mode but at least you can see the Table GUI. Type this in the terminal and press return:

defaults write com.transgui NSRequiresAquaSystemAppearance -bool yes

Then restart the app if it is open.


https://apple.stackexchange.com/questions/338044/can-i-turn-to-dark-mode-only-for-specific-apps-in-macos-mojave

**Comment by neo-neo1** [comment]
Hardly a workaround if it disables dark mode.

**Comment by BlackRockCity** [comment]
It only disables it for this particular application while leaving all others in dark mode. If your priority is to get the table to render properly, this is one method.

Sent from my iPhone

On Oct 24, 2020, at 11:36, neo-neo1 <notifications@github.com> wrote:

﻿

Hardly a workaround if it disables dark mode.

**Comment by hippydave** [comment]
Assuming from the above that the application uses Lazarus for its interface, there's example code to detect light/dark mode changes, including automatic mode, here:
https://wiki.lazarus.freepascal.org/Dark_theme#Example_2_2

It came from discussion in this thread:
https://forum.lazarus.freepascal.org/index.php?topic=43111.0

I hope the app can be updated to respond to mode changes, currently you either have to restart the app twice a day or disable dark mode for it, neither of which are ideal. Am happy to help with any testing etc.
