### ISSUE TITLE
Cannot manually type the port on the app (version 5.18.0 on macOS  Mojave)

### ISSUE THREAD

**Issue by mrjayviper** [transmission-remote-gui/transgui#1277]
as above.

Steps to reproduce

1. Go to manage connections
2. Change the port by manually typing it
3. Press ok to save changes 
4. Go back to manage connections

If i use the up/down arrows, it works fine.

Edit: temporary fix is to manually edit the ini file

**Comment by Flyingblu** [comment]
Same issue here. The similar issue seems to appear on a bunch of fields where it allows to key in the value as well as using the arrows. I think the author should repair this bug.

**Comment by jordanade** [comment]
Still have this issue.

**Comment by counterfit** [comment]
I've had this issue with changing upload/download speeds as well. Typed numbers don't take, but arrows do.
