### ISSUE TITLE
[Suggest] Search field on torrents list

### ISSUE THREAD

**Issue by saspol** [transmission-remote-gui/transgui#1290]
Hello,
It will be nice to have search field to filter torrents in list, like in many other apps for Mac. Otherwise very difficult to find anything if you seeding hundreds of torrents.
For example how this made in qBitttorrent:
https://monosnap.com/file/rQqFbCRB7OzvwkLVIkUxTpUxeqQjyB.png

**Comment by antekgla** [comment]
See https://github.com/transmission-remote-gui/transgui/issues/1154
