### ISSUE TITLE
Connection Timeout at connect

### ISSUE THREAD

**Issue by Diskutant** [transmission-remote-gui/transgui#1309]
I restarted my NAS the first time after a long time, now I can't connect to it's Transmission daemon with transgui anymore. 
I can see the CPU load on the NAS goes up when I try to connect.
Also I can connect to it using the webgui. 
That's why I think transgui does timeout too fast. I have quite a lot torrents in there, so I guess it needs to load quite a bunch of data which it can't do fast enough.

I found #1007 and changed the two timeout settings in the transgui.ini but that doesn't seem to have any effect while connecting to the daemon.

Is there any way to check if my assumption is right, and fix it?

Operating System: Win 10 Version 1909 
Deamon: 2.84 on Zyxel NAS
Remote GUI: v5.18.0

(also tested with v5.16.0 on macOS 10.14.6 with the same results)

**Comment by leonsoft-kras** [comment]
![image](https://user-images.githubusercontent.com/11468577/81940988-6bcef080-9622-11ea-9ab3-8f1863845a41.png)
- Find this program.
- Scan your port NAS.
- Is there access to the transmission?

**Comment by Diskutant** [comment]
I can't find that program. Do you have a link?

I tried Wireshark though. It shows the daemon is sending some data about my torrents and then seemingly gets stopped by the Transmission Remote GUI

In the screenshot packet 18501 is selected, which seem to stop the transfer.
The visible Packets 18455 to 18468 contain data about the torrents.

![transmissionWireshark](https://user-images.githubusercontent.com/898220/82136560-874b1e80-980f-11ea-9405-91edf95b7d97.png)

**Comment by leonsoft-kras** [comment]
1. The test showed that there is a connection.
2. I’m not sure whether the data were transferred to the AСK, especially about torrents.
3. I don’t know what is the reason for stopping the exchange.
4. Install the transmission on your local computer and try to compare Wireshark exchange. 
There will be some difference.

**Comment by Diskutant** [comment]
2. Yes there was data transferred about torrents. I can see the path and other info when I select that package.

3. I guess it's the RST, ACK package that is sent by Transmission Remote GUI

4. I compared the Wireshark exchange with my Transmission running on a different NAS, that one runs version 2.92 though. It shows the ACK packaged which contain the torrent information, but no RST, ACK package.

![saturn](https://user-images.githubusercontent.com/898220/82752792-d7eaea80-9dc0-11ea-83fe-6108a294e96b.png)

**Comment by leonsoft-kras** [comment]
need to understand. what the problem is so far unclear.

**Comment by Diskutant** [comment]
What can I do to make it clear?

**Comment by leonsoft-kras** [comment]
nothing. now no time to deal with this project.

**Comment by antekgla** [comment]
Have you tried another RPC client?
Why assume what TransGUI is the problem...? Like you say the problem begins when you restart your NAS. Maybe something in the RPC section in settings.json
Try another RPC client (not WebUI).
I use Transmission Remote by Yury Polek (search in Google Play) in my Android Phone, and works OK.
Only to discard what the problem is not in the server side with the RPC protocol.

**Comment by Diskutant** [comment]
the only other client I found (I don't have an Android Device) is this one: https://github.com/transmission-remote-gtk/transmission-remote-gtk

I launched VMWare with Ubuntu, compiled the latest git version of it. 
First try same result, a timeout occurs. After setting the timeout to 3600 it loaded about a minute, then everything worked as expected.

So my initial assumption seems right, the timeout value is too low in transmission-remote-gui

**Comment by antekgla** [comment]
What are your values for 
HttpTimeout=
ConnectTimeout=
in your Network section in transgui.ini?

**Comment by Diskutant** [comment]
Those are set to 3600, I tried different values with no change in behavior. The timeout message always shows up after 30 seconds.

[NetWork]
HttpTimeout=3600
ConnectTimeout=3600

**Comment by Diskutant** [comment]
by searching the source code i finally found the problem.

`i := Ini.ReadInteger('NetWork', 'HttpTimeout', 30);
  if (i < 2) or (i > 999) then i:= 30; // default`

set it to 999, now it finally works!

**Comment by antekgla** [comment]
Because the TimeOut is in SECONDS not miliseconds as usual...
