### ISSUE TITLE
Windows x64 - wrong dlls in 

### ISSUE THREAD

**Issue by atais** [transmission-remote-gui/transgui#1368]
1. Operating system
Windows 10 pro x64

3. Transmission Remote GUI
5.18.0 from releases

I had to download OpenSSL from 
https://indy.fulgan.com/SSL/openssl-1.0.2s-x64_86-win64.zip

Unpack libeay32.dll and ssleay32.dll to "C:\Program Files (x86)\Transmission Remote GUI" and restart client.

the included dlls did not work, resulting in the same error as in #1238

**Comment by g0blin-NN** [comment]
transgui-5.18.0-i386-win32.zip + openssl-1.0.2s-x64_86-win64.zip = does not work
transgui-5.18.0-x86_64-win64.zip + openssl-1.0.2s-x64_86-win64.zip = working

**Comment by g0blin-NN** [comment]
try it
https://github.com/pozitronik/CloudMailRu/tree/master/x64 for transgui win64
https://github.com/pozitronik/CloudMailRu/tree/master/x32 for transgui win32

**Comment by atais** [comment]
Maybe I have downloaded wrong one. Sorry
