### ISSUE TITLE
Feature request: allow adding many magnet links at once

### ISSUE THREAD

**Issue by FrostShock** [transmission-remote-gui/transgui#1381]
I have a text file containing links like these:

`magnet:?xt=urn:btih:D540FC48EB12F2833163EED6421D449DD8F1CE1F&dn=Ubuntu+desktop+19.04+%2864bit%29&tr=udp%3A%2F%2Ftracker..
magnet:?xt=urn:btih:5CDF31EDA177B6E1017634A3D9CB3B02F1C5E8D2&dn=LibreOffice+6.3.2+Windows+x64&tr=udp%3A%2F%2Ftracker..
magnet:?xt=urn:btih:0EACBBB2ADB0D33DCE98670378559A339DA2BA11&dn=Netbeans+7.0+Full+Windows+English&tr=udp%3A%2F%2Ftracker..`

I can copy the links then, when I open Transmission GUI, it will add them all to the download list. However,  I need to click OK/confirm for any of the downloads. That means that when adding 50 download links, I have to click "Ok" for 50 times.

I would like to ask to implement this feature: ask only once for adding all the links in the keyboard.

**Comment by antekgla** [comment]
Go to **Tools --> Application Options** and uncheck: **Promp for download options when adding new torrents**

**Comment by FrostShock** [comment]
This is quite awesome, many thanks! :+1:
