### ISSUE TITLE
Feature request - add a "#" or "Number" or "Index" column to the torrent list

### ISSUE THREAD

**Issue by FrostShock** [transmission-remote-gui/transgui#1383]
Please add a column to the torrent list with the index of the torrent (first torrent you add has index 1, the second has index 2 and so on) - it would help to manage torrents, to sort them by the order you added them in the list

Also would be nice to allow re-numbering them so you can easily count how many torrents you have in the list

**Comment by Mrnofish** [comment]
> Please add a column to the torrent list with the index of the torrent 

View > Setup Columns > [x] ID

> so you can easily count how many torrents you have in the list

View > Filter Pane

The torrent count appears next to each filter.
