### ISSUE TITLE
Apple Silicon M1 / ARM support

### ISSUE THREAD

**Issue by tcurdt** [transmission-remote-gui/transgui#1400]
I would like to run transmission-remote-gui on macOS 12 on an M1 chip.

It would be great if the build would create universal binaries. Is that in the cards?

Or are there any docs to build it myself for arm?

**Comment by PeterDaveHello** [comment]
Duplicated with https://github.com/transmission-remote-gui/transgui/issues/1355

**Comment by tcurdt** [comment]
Sorry, about the duplicate. Somehow missed the other one. Thanks!
