### ISSUE TITLE
TControl.InvalidatePreferredSize loop detected

### ISSUE THREAD

**Issue by bluenlive** [transmission-remote-gui/transgui#1459]
1. Operating System: Windows 10 x64 22H2 (19045.2965)
2. Transmission Daemon: 4.0.3-22 working on Synology DS418(DSM 7.1.1-42962 Update 5) / most recent versions
3. Transmission Remote GUI 5.18.0 (Fpc: 3.2.2 x64, Lazarus: 2.2.6.0 x64)

The error "TControl.InvalidatePreferredSize loop detected" occurs randomly.
It is not known in which cases it occurs.

![error](https://github.com/transmission-remote-gui/transgui/assets/2233617/d487b697-752c-41f1-9764-6972816ae2e5)

**Comment by xavery** [comment]
Reverting 89c4fa8882c3971e18ea314bec9d343bcda1fcfb seems to make this go away.

**Comment by bluenlive** [comment]
> Reverting [89c4fa8](https://github.com/transmission-remote-gui/transgui/commit/89c4fa8882c3971e18ea314bec9d343bcda1fcfb) seems to make this go away.

Thanks for your help.

**Comment by antivirtel** [comment]
Hi @bluenlive - I'm facing this issue too. Can you please create a release? There're no new releases since 2019. Thank you
