### ISSUE TITLE
"No route to host" in macOS Sequoia 15.0

### ISSUE THREAD

**Issue by tallest1** [transmission-remote-gui/transgui#1478]
### Discussed in https://github.com/transmission-remote-gui/transgui/discussions/1477

<div type='discussions-op-text'>

<sup>Originally posted by **tallest1** September 29, 2024</sup>
I'm getting the error "No route to host" running the GUI in macOS Sequoia 15.0 (connecting to a local server). I can successfully connect to the server using transmission-remote from the command line in macOS. 

I believe it's linked to the new "Local Network" settings under "Privacy & Security" in System Settings. The error is discussed in [dbeaver](https://github.com/dbeaver/dbeaver/issues/35705), [vscode](https://github.com/microsoft/vscode/issues/228862), [flutter](https://github.com/flutter/flutter/issues/150131), and [iacievedit.it](https://dev.iachieved.it/iachievedit/macos-sequoia-no-route-to-host/). 

Their solution involves toggling the switch for the app in the "Local Network" System Preferences pane, but Transmission Remote GUI isn't available there. </div>

**Comment by WWWXXX222** [comment]
Got same issue with MacOS 15.3 (24D60)

**Comment by recontemplator** [comment]
Got same issue. 
What helped me was deleting the application from the /Applications folder and then reinstalling it. 

Keep in mind that after reinstalling you will be not able to to just open app because of "malware prevention" system. You need to go to the Setting->security and choose "open anyway". After that it proposes to enable local network access to the app. Hope this helps.

**Comment by renatusgiovanni** [comment]
I also have this same issue. I tried what recontemplator was suggesting already.
Even after deleting and reinstalling x2goclient, and tell "use anyway" the MacBook did not had access to the server.
My Linux laptop and even my UTM Virtual Linux system worked just fine.
It is just this one app (x2goclient.app) that does not appear in the local network security list to toggle it.
My macOS version is 15.4, updated yesterday.

**Comment by mgoodall63** [comment]
MacOS Seqouia 15.4.1 has the same issue..

i cant see the app in privacy & Security - local network to re-enable it.

The web gui works fine..

**Comment by rafaferreirasantos** [comment]
Tha same here. Working through web browser but "No route to host" when using Transmission Remote GUI.

**Comment by rafaferreirasantos** [comment]
> Got same issue. What helped me was deleting the application from the /Applications folder and then reinstalling it.
> 
> Keep in mind that after reinstalling you will be not able to to just open app because of "malware prevention" system. You need to go to the Setting->security and choose "open anyway". After that it proposes to enable local network access to the app. Hope this helps.

Thanks. It worked for me.

**Comment by deekayw0n** [comment]
I think this may be related to "allow the application below to find and communicate with devices on your local network" setting. Even reinstalling on top of existing after macOS Tahoe installation I was still getting the same "No route to host" message. But once I deleted the app in Applications and dragged in the app from the installer DMG, I was prompted to allow access to local network, answered yes and viola.

**Comment by JayKuswahey** [comment]
MacOS Sequoia 15.7 (24G222)

I don't have Tahoe 26 installed, I installed the app through brew after a migration from M1 to M3 MBP. (I didn't want to install Rossetta2 at the start, but the lack of alternatives forced my hand).

I was able to do the "Open Anyway" action, but I had to reboot MacOS for the pop-up to show up that I could click Allow access to local resources.
