### ISSUE TITLE
Looks shit on retina display, thats all

### ISSUE THREAD

**Issue by GoogleCodeExporter** [transmission-remote-gui/transgui#818]
```
What steps will reproduce the problem?
1.
2.
3.

What is the expected output? What do you see instead?


What version of the product are you using? On what operating system?


Please provide any additional information below.

```

Original issue reported on code.google.com by `tomson...@gmail.com` on 8 Aug 2014 at 2:41

**Comment by mikaeldui** [comment]
Looks good on a high DPI Windows machine. Maybe Apple is shit?

**Comment by cryptochrome** [comment]
I can't confirm this. The UI properly scales on Retina displays. Does it look like a native macOS app? No. But it definitely has no issue with UI scaling (Retina).

**Comment by leonsoft-kras** [comment]
support for high DPI has been implemented, so this problem should already be in the past.
