### ISSUE TITLE
wrong context menu when renaming torrent in 5.20

### ISSUE THREAD

**Issue by rd1** [transmission-remote-gui/transgui#884]
when editing a torrent's name after adding, the context menu isn't the standard cut+copy+paste but the torrent operations menu and everything is grayed out.

just fyi v5.10 doesn't have this problem.

**Comment by rd1** [comment]
just to clarify, this happens in the list of torrents, after the torrent is added.

**Comment by leonsoft-kras** [comment]
please screenshot. I do not understand what you've done

**Comment by rd1** [comment]
F2 to rename a torrent, then right-click to open context menu.

notice as the menu isn't standard cut+copy+paste menu

![trg5 2](https://cloud.githubusercontent.com/assets/1567489/13831272/cd0f5a98-eba8-11e5-8c5c-95c31724056f.png)

**Comment by uniss2209** [comment]
Yes, I have the same problem. Only in version 5.1 the context menu corresponds to the task. I checked out later version 5.2 5.3 5.4 - in all, instead of the context menu is displayed the File menu with all inactive items.
Menu in 5.1
![2016-12-22 20-45-12](https://cloud.githubusercontent.com/assets/24721923/21436880/593725d8-c889-11e6-9f36-7490b1678de1.png)

Menu in 5.2 or later
![2016-12-22 20-09-01](https://cloud.githubusercontent.com/assets/24721923/21436871/4e370e50-c889-11e6-97f6-94f11810ff67.png)

**Comment by leonsoft-kras** [comment]
It seems the problem is associated with the transition to Lasarus 1.4.4. 
No changes have been in the code display of the context menu (I compared source the 5.1.0 and 5.2.0).

If there are to fix the problem - you are welcome.

**Comment by rd1** [comment]
the change to laz144 also must've broken the notifications, i haven't had one since 5.2

i've had to install transmission locally on a computer to be notified by the transmission backend instead of the gui made here.

**Comment by uniss2209** [comment]
Using Lazarus 1.4.4 is critical? It may be better to return to compile in the previous version?

**Comment by leonsoft-kras** [comment]
Perhaps in Lazarus something has changed with version 1.4 and above.
Life goes forward. Already a lot of different changes to compile the latest versions of Lazarus (in version 1.2 of the program is no longer compiled).

Now there are other urgent and important issues

**Comment by antekgla** [comment]
I solved this with the fix https://github.com/transmission-remote-gui/transgui/commit/2e7c2d5ec015efbb318b9cb258f915bde0eb9bdb

**Comment by PeterDaveHello** [comment]
v5.12.0 released

**Comment by rd1** [comment]
thanks PeterDaveHello, now the menu makes sense.

**Comment by PeterDaveHello** [comment]
Thanks @antekgla please :)
