### ISSUE TITLE
update peerblock list ?

### ISSUE THREAD

**Issue by rd1** [transmission-remote-gui/transgui#887]
we need an update button in the network options

**Comment by leonsoft-kras** [comment]
I did not understand what you mean.

**Comment by rd1** [comment]
open the transmission options from the gui
go in network (wan)

we can enter an url to a block list but we can't force it to update manually.

not all transmission servers have an auto-update for this list.

**Comment by PeterDaveHello** [comment]
@leonsoft-kras I think @rd1 means a button to request/check update of blocklist

**Comment by leonsoft-kras** [comment]
I do not understand the task.
And most importantly, I do not have the opportunity to test this task.

**Comment by rd1** [comment]
You can use this list 
http://list.iblocklist.com/?list=ydxerpxkpcfqjaybcssw&fileformat=p2p&archiveformat=gz

Also the original transmission backend from https://transmissionbt.com/ has this feature

**Comment by ploink** [comment]
You can update the blocklist from the main menu Tools -> Update blocklist.
I think @rd1 wants a button in the Transmission options -> Network (WAN) that does the same thing.

Something like the 'update' button in this screenshot:
https://digiex.net/attachments/screen-shot-2015-12-04-at-13-40-37-png.14443/

I think the button itself does not add any functionality, but a last update timestamp and number of rules in the list would be useful.

**Comment by PeterDaveHello** [comment]
I don't think this would be implemented, send a pull request if you really need it, otherwise, use the method from @ploink's comment please, it's pretty easy.
