### ISSUE TITLE
Feature req: bigger toolbar buttons and menu for touchscreen

### ISSUE THREAD

**Issue by rd1** [transmission-remote-gui/transgui#889]
just wondering if the bigger font idea can be extended to other parts of the gui for touch screens.

fingers are bigger than the buttons, it makes things difficult to tap them

i haven't tried on windows 10 as my tablet is win8.1 RT but it would make things easier to tap on screen.

**Comment by leonsoft-kras** [comment]
There is no need, as it will not solve your problem. Then you say that the finger does not fall in the list of torrents, so you need to change the font size, and other screen elements. Then you need to change all the dialogues in which many of the elements are the same small size.

**Comment by rd1** [comment]
problem is every element changes size, except the toolbar.

**Comment by rd1** [comment]
good work and also rhanks for the toolbar button for trg options, it makes more sense now

when we increase size of toolbar can we increase the size of the icons too ?

maybe allow right-click directly on toolbar to make bigger or smaller ?


thanks man, much appreciated :)

**Comment by rd1** [comment]
can we change F12 to F5 instead and add a show/hide info panel button on toolbar please ?

the button would really help with touchscreens

F5 isn't in use in TRG and is more inline with utorrent use of F5 to show/hide info panel.

An idea came to me, why not make a customizable toolbar like on windows explorer back in windows xp ?

we could right-click on it and show this window :

![404532 image0 1](https://cloud.githubusercontent.com/assets/1567489/14370175/5bcae6e2-fcf9-11e5-99a4-14dfc57c2bf3.jpg)

i nominate for buttons: everything in every menu. we can then choose exactly the toolbar we want.

**Comment by antekgla** [comment]
@leonsoft-kras any reason why you choose 64 as value for big buttons?
I am trying to work in #982 and I have to adapt it to bigtoolbar also and and I think what 48 would be a better value... but I dont have any touch screens to test the better size for this devices.

**Comment by rd1** [comment]
"but I dont have any touch screens to test the better size for this devices."
i think you just answered your own question there. please don't mess with the buttons. if anything make more stuff like "properties" when a torrent is chosen. or "move to" buttons.

**Comment by leonsoft-kras** [comment]
standard 32-pixel buttons. large buttons * 2.
That's how it turned out 64 pixels.

**Comment by antekgla** [comment]
With the commit https://github.com/transmission-remote-gui/transgui/commit/f7367b1248daa187dadd24acf5905422b0020163 made it for fix #982 also adds 32px Icons to Big Toolbar, also now there is a Menu Item for on/off (besides right click). With this new menu item is possible to assign a shortcut to change between small and big toolbar. Just modify **BigToolbar=**_{Shortcut here}_ in **[ShortCuts]** part of .ini file.

Also if someone want to modify the Bigtoolbar Height just add:

`BigToolBarHeight=48`

in the **[MainForm]** of transgui.ini (default still is 64).

**Toolbar Height=64**
![toolbar64_2](https://user-images.githubusercontent.com/24402722/33498727-2f5b4e42-d6b1-11e7-9d1f-e42816d3536a.jpg)

**Toolbar Height=48**
![toolbar48](https://user-images.githubusercontent.com/24402722/33498563-944c7174-d6b0-11e7-9ff0-9a4ac2e0f5f6.jpg)
