### ISSUE TITLE
ver 5.8.1

### ISSUE THREAD

**Issue by leonsoft-kras** [transmission-remote-gui/transgui#975]
Why create versions every few days?
What was done critical?

**Comment by PeterDaveHello** [comment]
hmmm ... I think it's the agile software development style, could not do that in future if you think it's not good.

**Comment by leonsoft-kras** [comment]
In my opinion, too little time has passed between 5.8 and 5.8.1.
I would understand the reason in a serious bug or the elimination of 1001 errors.

Look at Issue #919

**Comment by PeterDaveHello** [comment]
sure

**Comment by leonsoft-kras** [comment]
Is there any idea why the function stopped working in version 5.8 (#919)?

Version 5.7 was compiled by some standard methods. 
Probably used the old version of the Lazarus and the fpc. 
I compiled the last lazarus and fcp and the function does not work as it should.
May be the reason in the latest version of the lazarus ?

**Comment by PeterDaveHello** [comment]
What's their old version should be? Maybe try to use old ones to compile and test?

**Comment by leonsoft-kras** [comment]
1) There is an issue 919. I did not build a version for Linux in 5.7. 
The latest changes to the source code did not concern the issue 919. 
I suggest that other developers build version 5.8 similarly as version 5.7.

2) Why did you delete the readme.txt file ?????
I know that this file opens in Windows and Linux. 
What is the *.md file? 
What will ordinary users see it? 
Why was it done ?
I suggest leaving the usual text file readme.txt in the project and distribution.

**Comment by PeterDaveHello** [comment]
Just move to readme.md, which GitHub can parse and display beautifully, it's still a text file.
See the difference:
 - https://github.com/leonsoft-kras/transmisson-remote-gui/blob/master/README.md
 - https://github.com/leonsoft-kras/transmisson-remote-gui/blob/master/readme.txt

**Comment by PeterDaveHello** [comment]
See this doc for more details:
https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/

**Comment by leonsoft-kras** [comment]
But where is the githab? 
This file is now placed in the distribution for ordinary users. What will they do with it?
![111111](https://user-images.githubusercontent.com/11468577/28248547-7a5f46ee-6a70-11e7-8380-0da508d8cc47.png)

**Comment by PeterDaveHello** [comment]
For the new parsed looking, take a look at the homepage please:
https://github.com/leonsoft-kras/transmisson-remote-gui/

On windows, you can choose notepad or any text editor to open it.

**Comment by PeterDaveHello** [comment]
For #919, I have no idea what's the old compilation environment should be yet, I'm not sure if somebody else knows that properly. Looks like we can't say the problem is caused by compiler right now, unless we compiled the same source with different compilers, and the old one working, the new one broken.

Using Travis CI to build/compile the release makes everything in public, traceable. If we need, we can still change to use an older compiler on it.

**Comment by PeterDaveHello** [comment]
If there is a concern about the prompt window about how to open *.md file, maybe we can just register notepad for it as the default application to open it, if *.md is not registered on that computer yet.

**Comment by leonsoft-kras** [comment]
1) I don't understand why reinvent the wheel. 
I don't want to register anything in Windows  (this file is additionally displayed in the installer of the program and I suspect crookedly).

2) If the source code has not changed, then I assume that the case is in the compiler or Linux. Precisely, no one will say. Now we are assembling the Lazarus 1.6.4, fpc 3.0.2.
I don't know which version of the compiler version 5.7 was built for Linux.
Probably should show the version of the compiler and the lazarus in the window "about the program".

**Comment by duramato** [comment]
>In my opinion, too little time has passed between 5.8 and 5.8.1.
I would understand the reason in a serious bug or the elimination of 1001 errors.

It seems to me you are using semantic versioning http://semver.org/#semantic-versioning-specification-semver, respecting that, imo bugfixes or hotfixes shouldn't obbey normal release schedule.

**Comment by PeterDaveHello** [comment]
It's not reinventing the wheel, using markdown to provide a formatted, rich content is the trend, don't you agree the current readme in the homepage is much more easier to be reading and understanding with the parsed structure? If it's just additionally displayed in installer, maybe we can just call notepad to open it, which may be easier.

**Comment by leonsoft-kras** [comment]
Again. I do not mind this format on the web page. I do not understand why he told me and others on the disk with the program? I suggest leaving the text version of the file in the installer.

That it was understandable. Let's save the html-page on the disk as a file readme.ddd. Let users open this file with a notebook for study.

**Comment by PeterDaveHello** [comment]
IMO, we can just copy the `README.md` to `readme.txt` in the Windows release build process, we don't need to maintain two different files, most of the parts in markdown format are directly human readable even you don't know its meaning, you can talk a look at this: https://raw.githubusercontent.com/leonsoft-kras/transmisson-remote-gui/master/README.md as an example, what do you think?

**Comment by leonsoft-kras** [comment]
1. I added both files to the installer.
2. Of course the file can be viewed with markup. It's almost as convenient as watching html markup
3. The file on the githab (with markup) looks great.
4. I would understand the inclusion of an html or mht file in the installer.
5. Link to the site with the file (for viewing) is not needed. The site may disappear by link. The user may not have the Internet, etc.

We have been discussing this issue for a long time.

**Comment by PeterDaveHello** [comment]
I'm not sure I really understand your comment, some of "markup"s seem to mean "markdown" but some not but its own origin meaning.

Just a updates here, from now on every non-tagged/released commit, their build assets would also be uploaded on the cloud so that we can easier to test them. The file would live for a week, and the url would be in the part of `Deploying application` in the Travis CI build log.

Take this build as example: https://travis-ci.org/leonsoft-kras/transmisson-remote-gui/builds/255732578

[linux x86](https://travis-ci.org/leonsoft-kras/transmisson-remote-gui/jobs/255732582):
```
 Uploading ./Release/transgui-5.8.1-i386-linux.zip ...
 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1404k  100    81  100 1404k    177  3071k --:--:-- --:--:-- --:--:-- 3067k
./Release/transgui-5.8.1-i386-linux.zip uploaded with success!!!
Download url: https://file.io/WtJeM1 (expires in 1 week)
```

[linux amd64](https://travis-ci.org/leonsoft-kras/transmisson-remote-gui/jobs/255732581):
```
Uploading ./Release/transgui-5.8.1-x86_64-linux.zip ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1548k  100    81  100 1548k    178  3416k --:--:-- --:--:-- --:--:-- 3418k
./Release/transgui-5.8.1-x86_64-linux.zip uploaded with success!!!
Download url: https://file.io/anDZ2p (expires in 1 week)
```

[macOS](https://travis-ci.org/leonsoft-kras/transmisson-remote-gui/jobs/255732583):
```
Uploading ./setup/macosx/transgui-5.8.1.dmg ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1476k  100    81  100 1476k     75  1367k  0:00:01  0:00:01 --:--:-- 1368k
./setup/macosx/transgui-5.8.1.dmg uploaded with success!!!
Download url: https://file.io/VTFirf (expires in 1 week)
```

**Comment by leonsoft-kras** [comment]
I study it. Thank you

**Comment by PeterDaveHello** [comment]
@leonsoft-kras can you please help build the Windows release for [v5.8.2](https://github.com/leonsoft-kras/transmisson-remote-gui/releases/tag/v5.8.2)? Thanks.
