### ISSUE TITLE
Hungarian language file (for TransGUI 5.8.1)

### ISSUE THREAD

**Issue by ghost** [transmission-remote-gui/transgui#976]
A brand new Hungarian language file - based on transgui.template: 
[transgui.zip](https://github.com/leonsoft-kras/transmisson-remote-gui/files/1136651/transgui.zip)

**Comment by PeterDaveHello** [comment]
@novamaxx would you like to send a pull request for it so that you'll be listed as one of our contributors here: https://github.com/leonsoft-kras/transmisson-remote-gui/graphs ? 😄

**Comment by novamaxx** [comment]
@PeterDaveHello Thanks, maybe a little later. :)

**Comment by PeterDaveHello** [comment]
Just to confirm, so you prefer to let us to directly update it first?

**Comment by PeterDaveHello** [comment]
Looks like the reporter account was deleted, if there are some people can help valid the translation recenlt, I'll merge it, or maybe just close it.

**Comment by stsmurfy** [comment]
That translation seems good.
