### ISSUE TITLE
Easy switching and visible connexion name

### ISSUE THREAD

**Issue by pierrandre** [transmission-remote-gui/transgui#982]
Hello,

I manage several Transmission servers, and always switching between servers is a bit annoying
the following would be great improvements to your program:

- the window title would reflect the connexion name (or the connexion button would display the connexion name)
- there would be a new buttons bar with easy switching between connexions, or a tab system with all your connexions à-la-Chrome

Thanks for considering those

**Comment by antekgla** [comment]
With commit https://github.com/transmission-remote-gui/transgui/commit/f7367b1248daa187dadd24acf5905422b0020163 I added the Connexion Name in Connect button for easy readibility

![toolbar48](https://user-images.githubusercontent.com/24402722/33498852-abe5d6bc-d6b1-11e7-9dbb-19a6c659509a.jpg)

**Comment by PeterDaveHello** [comment]
1.
