### ISSUE TITLE
Strange 0 size duplication of folders in "Files" tab

### ISSUE THREAD

**Issue by vinaydvlp** [transmission-remote-gui/transgui#997]
Seeing this weird duplication of folders in the files tab. This duplication also occurs when adding the torrent. No duplication of folders visible when adding torrent through transmission gui that comes with linux mint. I've seen this in some torrents that have a lot of folders in them. 

Using Transmission Remote GUI 5.8.2 build 4a1d195
OS - Linux Mint 18.1

![folder duplicates](https://user-images.githubusercontent.com/18628473/29249698-42d9f87a-8052-11e7-95a1-760693a1abd3.png)

I don't know if linking to the torrent is allowed so not doing that.

**Comment by leonsoft-kras** [comment]
I've never come across this before. Perhaps this is a question for the torrent file.

**Comment by vinaydvlp** [comment]
Please close the issue. I forgot in which new version this duplication stopped.
This is not happening anymore in the newer versions of the app on linux.
